// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'interpreter.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'risk.dart';
import 'scaling.dart';
import 'telegram.dart';
import 'weex.dart';

// These functions are ignored because they are not marked as `pub`: `chart_history`, `classify_message_actions_with_rules`, `push_point`, `weex_rejection_message`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `StateView`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Stream<PriceTick> weexPublicPriceStream() => RustLib.instance.api.crateApiWeexPublicPriceStream();

Stream<TelegramMessageEvent> telegramMessageStream({required TelegramClientRequest request}) =>
    RustLib.instance.api.crateApiTelegramMessageStream(request: request);

Future<ApiResultTelegramLoginStatus> telegramRequestCode({
  required TelegramClientRequest request,
}) => RustLib.instance.api.crateApiTelegramRequestCode(request: request);

Future<ApiResultTelegramLoginStatus> telegramSignIn({required String code}) =>
    RustLib.instance.api.crateApiTelegramSignIn(code: code);

Future<ApiResultTelegramLoginStatus> telegramCheckPassword({required String password}) =>
    RustLib.instance.api.crateApiTelegramCheckPassword(password: password);

Future<ApiResultString> telegramFinalizeAction({
  required String statePath,
  required String dedupKey,
  required TelegramActionStatus status,
  String? orderId,
}) => RustLib.instance.api.crateApiTelegramFinalizeAction(
  statePath: statePath,
  dedupKey: dedupKey,
  status: status,
  orderId: orderId,
);

/// Seals `credentials_json` into `<dir>/credentials.enc`.
Future<ApiResultString> secretsSave({required String dir, required String credentialsJson}) =>
    RustLib.instance.api.crateApiSecretsSave(dir: dir, credentialsJson: credentialsJson);

/// Opens `<dir>/credentials.enc`. `value` is null when nothing is stored or the
/// blob cannot be opened on this install.
Future<ApiResultString> secretsLoad({required String dir}) =>
    RustLib.instance.api.crateApiSecretsLoad(dir: dir);

Future<ApiResultString> secretsPurge({required String dir}) =>
    RustLib.instance.api.crateApiSecretsPurge(dir: dir);

/// Tightens permissions on the data directory and the secrets inside it.
Future<ApiResultString> secretsHarden({required String dir}) =>
    RustLib.instance.api.crateApiSecretsHarden(dir: dir);

Future<void> riskSetLimits({required RiskLimits limits}) =>
    RustLib.instance.api.crateApiRiskSetLimits(limits: limits);

Future<RiskLimits> riskLimits() => RustLib.instance.api.crateApiRiskLimits();

/// Feeds the gate the live account facts it compares limits against.
Future<void> riskUpdateContext({required RiskContext context}) =>
    RustLib.instance.api.crateApiRiskUpdateContext(context: context);

Future<RiskContext> riskContext() => RustLib.instance.api.crateApiRiskContext();

/// Dry-runs the gate so the UI can warn before an order is ever sent.
/// `value` is null when the order passes; otherwise it is the rejection reason.
Future<ApiResultString> riskPreviewOrder({
  required String symbol,
  required double qtyBtc,
  required bool reduceOnly,
}) => RustLib.instance.api.crateApiRiskPreviewOrder(
  symbol: symbol,
  qtyBtc: qtyBtc,
  reduceOnly: reduceOnly,
);

/// `value` is null when the signal is fresh enough, otherwise the reason.
Future<ApiResultString> riskCheckSignalAge({
  required PlatformInt64 messageTimestampMs,
  required PlatformInt64 nowMs,
}) => RustLib.instance.api.crateApiRiskCheckSignalAge(
  messageTimestampMs: messageTimestampMs,
  nowMs: nowMs,
);

/// Actions that were reserved but never finalized, newest first. Each is an
/// order we may or may not have placed.
Future<ApiResultPendingActions> dedupPendingActions({required String statePath}) =>
    RustLib.instance.api.crateApiDedupPendingActions(statePath: statePath);

/// Asks the exchange what became of one `client_order_id`.
///
/// An error means "could not determine" — never retry on the strength of it.
/// `ok` with `found: false` means the exchange has no such order.
Future<ApiResultWeexOrderStatus> weexLookupOrder({
  required WeexAccountRequest request,
  required String clientOrderId,
}) => RustLib.instance.api.crateApiWeexLookupOrder(request: request, clientOrderId: clientOrderId);

Future<ApiResultWeexAccountReconciliation> weexReconcileAccount({
  required WeexAccountRequest request,
}) => RustLib.instance.api.crateApiWeexReconcileAccount(request: request);

Future<ApiResultWeexMarketOrderAck> weexSubmitMarketOrder({
  required WeexMarketOrderRequest request,
}) => RustLib.instance.api.crateApiWeexSubmitMarketOrder(request: request);

Future<ApiResultWeexMarketOrderAck> weexSubmitAlgoOrder({required WeexAlgoOrderRequest request}) =>
    RustLib.instance.api.crateApiWeexSubmitAlgoOrder(request: request);

Future<ApiResultWeexMarketOrderAck> weexSubmitTpSlOrder({required WeexTpSlOrderRequest request}) =>
    RustLib.instance.api.crateApiWeexSubmitTpSlOrder(request: request);

Future<ApiResultWeexMarketOrderAck> weexCancelAlgoOrder({required WeexCancelAlgoRequest request}) =>
    RustLib.instance.api.crateApiWeexCancelAlgoOrder(request: request);

/// TAKE_PROFIT or STOP_LOSS for a target price against an open position.
Future<String> weexTpSlPlanType({
  required Direction direction,
  required double triggerPrice,
  required double markPrice,
}) => RustLib.instance.api.crateApiWeexTpSlPlanType(
  direction: direction,
  triggerPrice: triggerPrice,
  markPrice: markPrice,
);

Future<void> recordChartSnapshot({
  required PlatformInt64 timestampMs,
  required double balance,
  required double equity,
  required double cumulativePnl,
}) => RustLib.instance.api.crateApiRecordChartSnapshot(
  timestampMs: timestampMs,
  balance: balance,
  equity: equity,
  cumulativePnl: cumulativePnl,
);

Future<ChartData> getChartData() => RustLib.instance.api.crateApiGetChartData();

Future<List<SeriesPoint>> getBalanceHistory() => RustLib.instance.api.crateApiGetBalanceHistory();

Future<List<SeriesPoint>> getEquityHistory() => RustLib.instance.api.crateApiGetEquityHistory();

Future<List<SeriesPoint>> getPnlHistory() => RustLib.instance.api.crateApiGetPnlHistory();

Future<CloseTarget?> extractCloseTarget({required String text}) =>
    RustLib.instance.api.crateApiExtractCloseTarget(text: text);

Future<double?> extractMasterBalance({required String text}) =>
    RustLib.instance.api.crateApiExtractMasterBalance(text: text);

Future<bool> closeTargetShouldFire({
  required Direction direction,
  required double price,
  required double low,
  required double high,
}) => RustLib.instance.api.crateApiCloseTargetShouldFire(
  direction: direction,
  price: price,
  low: low,
  high: high,
);

Future<ApiResultAction> classifyMessage({required String text}) =>
    RustLib.instance.api.crateApiClassifyMessage(text: text);

Future<ApiResultActions> classifyMessageActions({required String text}) =>
    RustLib.instance.api.crateApiClassifyMessageActions(text: text);

Future<String> defaultPatternsYaml() => RustLib.instance.api.crateApiDefaultPatternsYaml();

Future<ApiResultString> validatePatternsYaml({required String patternsYaml}) =>
    RustLib.instance.api.crateApiValidatePatternsYaml(patternsYaml: patternsYaml);

Future<ApiResultString> mergePatternsYaml({required String baseYaml, required String localYaml}) =>
    RustLib.instance.api.crateApiMergePatternsYaml(baseYaml: baseYaml, localYaml: localYaml);

Future<ApiResultActions> classifyMessageActionsWithPatterns({
  required String text,
  required String patternsYaml,
}) => RustLib.instance.api.crateApiClassifyMessageActionsWithPatterns(
  text: text,
  patternsYaml: patternsYaml,
);

Future<ApiResultScaledOrder> scaleManualOrder({required ManualScaleRequest request}) =>
    RustLib.instance.api.crateApiScaleManualOrder(request: request);

Future<ApiResultString> weexSignPreview({
  required String secret,
  required PlatformInt64 timestamp,
  required String method,
  required String path,
  required String query,
  required String body,
}) => RustLib.instance.api.crateApiWeexSignPreview(
  secret: secret,
  timestamp: timestamp,
  method: method,
  path: path,
  query: query,
  body: body,
);

Future<String> hello() => RustLib.instance.api.crateApiHello();

class ApiResultAction {
  final bool ok;
  final Action? value;
  final String? error;

  const ApiResultAction({required this.ok, this.value, this.error});

  @override
  int get hashCode => ok.hashCode ^ value.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiResultAction &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          value == other.value &&
          error == other.error;
}

class ApiResultActions {
  final bool ok;
  final List<Action>? value;
  final String? error;

  const ApiResultActions({required this.ok, this.value, this.error});

  @override
  int get hashCode => ok.hashCode ^ value.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiResultActions &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          value == other.value &&
          error == other.error;
}

class ApiResultPendingActions {
  final bool ok;
  final List<PendingAction>? value;
  final String? error;

  const ApiResultPendingActions({required this.ok, this.value, this.error});

  @override
  int get hashCode => ok.hashCode ^ value.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiResultPendingActions &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          value == other.value &&
          error == other.error;
}

class ApiResultScaledOrder {
  final bool ok;
  final ScaledOrder? value;
  final String? error;

  const ApiResultScaledOrder({required this.ok, this.value, this.error});

  @override
  int get hashCode => ok.hashCode ^ value.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiResultScaledOrder &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          value == other.value &&
          error == other.error;
}

class ApiResultString {
  final bool ok;
  final String? value;
  final String? error;

  const ApiResultString({required this.ok, this.value, this.error});

  @override
  int get hashCode => ok.hashCode ^ value.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiResultString &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          value == other.value &&
          error == other.error;
}

class ApiResultTelegramLoginStatus {
  final bool ok;
  final TelegramLoginStatus? value;
  final String? error;

  const ApiResultTelegramLoginStatus({required this.ok, this.value, this.error});

  @override
  int get hashCode => ok.hashCode ^ value.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiResultTelegramLoginStatus &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          value == other.value &&
          error == other.error;
}

class ApiResultWeexAccountReconciliation {
  final bool ok;
  final WeexAccountReconciliation? value;
  final String? error;

  const ApiResultWeexAccountReconciliation({required this.ok, this.value, this.error});

  @override
  int get hashCode => ok.hashCode ^ value.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiResultWeexAccountReconciliation &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          value == other.value &&
          error == other.error;
}

class ApiResultWeexMarketOrderAck {
  final bool ok;
  final WeexMarketOrderAck? value;
  final String? error;

  const ApiResultWeexMarketOrderAck({required this.ok, this.value, this.error});

  @override
  int get hashCode => ok.hashCode ^ value.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiResultWeexMarketOrderAck &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          value == other.value &&
          error == other.error;
}

class ApiResultWeexOrderStatus {
  final bool ok;
  final WeexOrderStatus? value;
  final String? error;

  const ApiResultWeexOrderStatus({required this.ok, this.value, this.error});

  @override
  int get hashCode => ok.hashCode ^ value.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiResultWeexOrderStatus &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          value == other.value &&
          error == other.error;
}

class ChartData {
  final List<SeriesPoint> balance;
  final List<SeriesPoint> equity;
  final List<SeriesPoint> pnl;

  const ChartData({required this.balance, required this.equity, required this.pnl});

  static Future<ChartData> default_() => RustLib.instance.api.crateApiChartDataDefault();

  @override
  int get hashCode => balance.hashCode ^ equity.hashCode ^ pnl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChartData &&
          runtimeType == other.runtimeType &&
          balance == other.balance &&
          equity == other.equity &&
          pnl == other.pnl;
}

class CloseTarget {
  final double low;
  final double high;

  const CloseTarget({required this.low, required this.high});

  @override
  int get hashCode => low.hashCode ^ high.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CloseTarget &&
          runtimeType == other.runtimeType &&
          low == other.low &&
          high == other.high;
}

class ManualScaleRequest {
  final double amount;
  final ManualSizeUnit unit;
  final double masterBalanceUsd;
  final double myBalanceUsd;
  final double markPrice;
  final double qtyStep;

  const ManualScaleRequest({
    required this.amount,
    required this.unit,
    required this.masterBalanceUsd,
    required this.myBalanceUsd,
    required this.markPrice,
    required this.qtyStep,
  });

  @override
  int get hashCode =>
      amount.hashCode ^
      unit.hashCode ^
      masterBalanceUsd.hashCode ^
      myBalanceUsd.hashCode ^
      markPrice.hashCode ^
      qtyStep.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ManualScaleRequest &&
          runtimeType == other.runtimeType &&
          amount == other.amount &&
          unit == other.unit &&
          masterBalanceUsd == other.masterBalanceUsd &&
          myBalanceUsd == other.myBalanceUsd &&
          markPrice == other.markPrice &&
          qtyStep == other.qtyStep;
}

enum ManualSizeUnit { btc, usdt }

/// An action reserved in the dedup store that never reached a final status.
class PendingAction {
  final String dedupKey;
  final PlatformInt64 channelId;
  final PlatformInt64 messageId;
  final int actionOrdinal;
  final PlatformInt64 updatedAtMs;

  const PendingAction({
    required this.dedupKey,
    required this.channelId,
    required this.messageId,
    required this.actionOrdinal,
    required this.updatedAtMs,
  });

  @override
  int get hashCode =>
      dedupKey.hashCode ^
      channelId.hashCode ^
      messageId.hashCode ^
      actionOrdinal.hashCode ^
      updatedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PendingAction &&
          runtimeType == other.runtimeType &&
          dedupKey == other.dedupKey &&
          channelId == other.channelId &&
          messageId == other.messageId &&
          actionOrdinal == other.actionOrdinal &&
          updatedAtMs == other.updatedAtMs;
}

class SeriesPoint {
  final PlatformInt64 timestampMs;
  final double value;

  const SeriesPoint({required this.timestampMs, required this.value});

  @override
  int get hashCode => timestampMs.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SeriesPoint &&
          runtimeType == other.runtimeType &&
          timestampMs == other.timestampMs &&
          value == other.value;
}
