// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';
import 'interpreter.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'scaling.dart';
import 'telegram.dart';
import 'weex.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor => RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor => RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 878231375;

  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
    stem: 'trading_challenge_core',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<ChartData> crateApiChartDataDefault();

  Future<ApiResultAction> crateApiClassifyMessage({required String text});

  Future<List<SeriesPoint>> crateApiGetBalanceHistory();

  Future<ChartData> crateApiGetChartData();

  Future<List<SeriesPoint>> crateApiGetEquityHistory();

  Future<List<SeriesPoint>> crateApiGetPnlHistory();

  Future<String> crateApiHello();

  Future<void> crateApiRecordChartSnapshot({
    required PlatformInt64 timestampMs,
    required double balance,
    required double equity,
    required double cumulativePnl,
  });

  Future<ApiResultScaledOrder> crateApiScaleManualOrder({required ManualScaleRequest request});

  Future<ApiResultTelegramLoginStatus> crateApiTelegramCheckPassword({required String password});

  Future<ApiResultString> crateApiTelegramFinalizeAction({
    required String statePath,
    required String dedupKey,
    required TelegramActionStatus status,
    String? orderId,
  });

  Stream<TelegramMessageEvent> crateApiTelegramMessageStream({
    required TelegramClientRequest request,
  });

  Future<ApiResultTelegramLoginStatus> crateApiTelegramRequestCode({
    required TelegramClientRequest request,
  });

  Future<ApiResultTelegramLoginStatus> crateApiTelegramSignIn({required String code});

  Stream<PriceTick> crateApiWeexPublicPriceStream();

  Future<ApiResultWeexAccountReconciliation> crateApiWeexReconcileAccount({
    required WeexAccountRequest request,
  });

  Future<ApiResultString> crateApiWeexSignPreview({
    required String secret,
    required PlatformInt64 timestamp,
    required String method,
    required String path,
    required String query,
    required String body,
  });

  Future<ApiResultWeexMarketOrderAck> crateApiWeexSubmitMarketOrder({
    required WeexMarketOrderRequest request,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<ChartData> crateApiChartDataDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_chart_data, decodeErrorData: null),
        constMeta: kCrateApiChartDataDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChartDataDefaultConstMeta =>
      const TaskConstMeta(debugName: "chart_data_default", argNames: []);

  @override
  Future<ApiResultAction> crateApiClassifyMessage({required String text}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_api_result_action, decodeErrorData: null),
        constMeta: kCrateApiClassifyMessageConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClassifyMessageConstMeta =>
      const TaskConstMeta(debugName: "classify_message", argNames: ["text"]);

  @override
  Future<List<SeriesPoint>> crateApiGetBalanceHistory() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_list_series_point, decodeErrorData: null),
        constMeta: kCrateApiGetBalanceHistoryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetBalanceHistoryConstMeta =>
      const TaskConstMeta(debugName: "get_balance_history", argNames: []);

  @override
  Future<ChartData> crateApiGetChartData() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_chart_data, decodeErrorData: null),
        constMeta: kCrateApiGetChartDataConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetChartDataConstMeta =>
      const TaskConstMeta(debugName: "get_chart_data", argNames: []);

  @override
  Future<List<SeriesPoint>> crateApiGetEquityHistory() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_list_series_point, decodeErrorData: null),
        constMeta: kCrateApiGetEquityHistoryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetEquityHistoryConstMeta =>
      const TaskConstMeta(debugName: "get_equity_history", argNames: []);

  @override
  Future<List<SeriesPoint>> crateApiGetPnlHistory() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_list_series_point, decodeErrorData: null),
        constMeta: kCrateApiGetPnlHistoryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetPnlHistoryConstMeta =>
      const TaskConstMeta(debugName: "get_pnl_history", argNames: []);

  @override
  Future<String> crateApiHello() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_String, decodeErrorData: null),
        constMeta: kCrateApiHelloConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHelloConstMeta =>
      const TaskConstMeta(debugName: "hello", argNames: []);

  @override
  Future<void> crateApiRecordChartSnapshot({
    required PlatformInt64 timestampMs,
    required double balance,
    required double equity,
    required double cumulativePnl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(timestampMs, serializer);
          sse_encode_f_64(balance, serializer);
          sse_encode_f_64(equity, serializer);
          sse_encode_f_64(cumulativePnl, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_unit, decodeErrorData: null),
        constMeta: kCrateApiRecordChartSnapshotConstMeta,
        argValues: [timestampMs, balance, equity, cumulativePnl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecordChartSnapshotConstMeta => const TaskConstMeta(
    debugName: "record_chart_snapshot",
    argNames: ["timestampMs", "balance", "equity", "cumulativePnl"],
  );

  @override
  Future<ApiResultScaledOrder> crateApiScaleManualOrder({required ManualScaleRequest request}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_manual_scale_request(request, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_result_scaled_order,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScaleManualOrderConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScaleManualOrderConstMeta =>
      const TaskConstMeta(debugName: "scale_manual_order", argNames: ["request"]);

  @override
  Future<ApiResultTelegramLoginStatus> crateApiTelegramCheckPassword({required String password}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(password, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_result_telegram_login_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTelegramCheckPasswordConstMeta,
        argValues: [password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTelegramCheckPasswordConstMeta =>
      const TaskConstMeta(debugName: "telegram_check_password", argNames: ["password"]);

  @override
  Future<ApiResultString> crateApiTelegramFinalizeAction({
    required String statePath,
    required String dedupKey,
    required TelegramActionStatus status,
    String? orderId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(statePath, serializer);
          sse_encode_String(dedupKey, serializer);
          sse_encode_telegram_action_status(status, serializer);
          sse_encode_opt_String(orderId, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_api_result_string, decodeErrorData: null),
        constMeta: kCrateApiTelegramFinalizeActionConstMeta,
        argValues: [statePath, dedupKey, status, orderId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTelegramFinalizeActionConstMeta => const TaskConstMeta(
    debugName: "telegram_finalize_action",
    argNames: ["statePath", "dedupKey", "status", "orderId"],
  );

  @override
  Stream<TelegramMessageEvent> crateApiTelegramMessageStream({
    required TelegramClientRequest request,
  }) {
    final sink = RustStreamSink<TelegramMessageEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_box_autoadd_telegram_client_request(request, serializer);
            sse_encode_StreamSink_telegram_message_event_Sse(sink, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12, port: port_);
          },
          codec: SseCodec(decodeSuccessData: sse_decode_unit, decodeErrorData: null),
          constMeta: kCrateApiTelegramMessageStreamConstMeta,
          argValues: [request, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiTelegramMessageStreamConstMeta =>
      const TaskConstMeta(debugName: "telegram_message_stream", argNames: ["request", "sink"]);

  @override
  Future<ApiResultTelegramLoginStatus> crateApiTelegramRequestCode({
    required TelegramClientRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_telegram_client_request(request, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_result_telegram_login_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTelegramRequestCodeConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTelegramRequestCodeConstMeta =>
      const TaskConstMeta(debugName: "telegram_request_code", argNames: ["request"]);

  @override
  Future<ApiResultTelegramLoginStatus> crateApiTelegramSignIn({required String code}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(code, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_result_telegram_login_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTelegramSignInConstMeta,
        argValues: [code],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTelegramSignInConstMeta =>
      const TaskConstMeta(debugName: "telegram_sign_in", argNames: ["code"]);

  @override
  Stream<PriceTick> crateApiWeexPublicPriceStream() {
    final sink = RustStreamSink<PriceTick>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_price_tick_Sse(sink, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15, port: port_);
          },
          codec: SseCodec(decodeSuccessData: sse_decode_unit, decodeErrorData: null),
          constMeta: kCrateApiWeexPublicPriceStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiWeexPublicPriceStreamConstMeta =>
      const TaskConstMeta(debugName: "weex_public_price_stream", argNames: ["sink"]);

  @override
  Future<ApiResultWeexAccountReconciliation> crateApiWeexReconcileAccount({
    required WeexAccountRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_weex_account_request(request, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_result_weex_account_reconciliation,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWeexReconcileAccountConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWeexReconcileAccountConstMeta =>
      const TaskConstMeta(debugName: "weex_reconcile_account", argNames: ["request"]);

  @override
  Future<ApiResultString> crateApiWeexSignPreview({
    required String secret,
    required PlatformInt64 timestamp,
    required String method,
    required String path,
    required String query,
    required String body,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(secret, serializer);
          sse_encode_i_64(timestamp, serializer);
          sse_encode_String(method, serializer);
          sse_encode_String(path, serializer);
          sse_encode_String(query, serializer);
          sse_encode_String(body, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17, port: port_);
        },
        codec: SseCodec(decodeSuccessData: sse_decode_api_result_string, decodeErrorData: null),
        constMeta: kCrateApiWeexSignPreviewConstMeta,
        argValues: [secret, timestamp, method, path, query, body],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWeexSignPreviewConstMeta => const TaskConstMeta(
    debugName: "weex_sign_preview",
    argNames: ["secret", "timestamp", "method", "path", "query", "body"],
  );

  @override
  Future<ApiResultWeexMarketOrderAck> crateApiWeexSubmitMarketOrder({
    required WeexMarketOrderRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_weex_market_order_request(request, serializer);
          pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18, port: port_);
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_result_weex_market_order_ack,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWeexSubmitMarketOrderConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWeexSubmitMarketOrderConstMeta =>
      const TaskConstMeta(debugName: "weex_submit_market_order", argNames: ["request"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<PriceTick> dco_decode_StreamSink_price_tick_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<TelegramMessageEvent> dco_decode_StreamSink_telegram_message_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Action dco_decode_action(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6) throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return Action(
      kind: dco_decode_action_kind(arr[0]),
      direction: dco_decode_opt_box_autoadd_direction(arr[1]),
      size: dco_decode_opt_box_autoadd_size(arr[2]),
      confidenceHigh: dco_decode_bool(arr[3]),
      needsApproval: dco_decode_bool(arr[4]),
      rawText: dco_decode_String(arr[5]),
    );
  }

  @protected
  ActionKind dco_decode_action_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ActionKind.values[raw as int];
  }

  @protected
  ApiResultAction dco_decode_api_result_action(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ApiResultAction(
      ok: dco_decode_bool(arr[0]),
      value: dco_decode_opt_box_autoadd_action(arr[1]),
      error: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  ApiResultScaledOrder dco_decode_api_result_scaled_order(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ApiResultScaledOrder(
      ok: dco_decode_bool(arr[0]),
      value: dco_decode_opt_box_autoadd_scaled_order(arr[1]),
      error: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  ApiResultString dco_decode_api_result_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ApiResultString(
      ok: dco_decode_bool(arr[0]),
      value: dco_decode_opt_String(arr[1]),
      error: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  ApiResultTelegramLoginStatus dco_decode_api_result_telegram_login_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ApiResultTelegramLoginStatus(
      ok: dco_decode_bool(arr[0]),
      value: dco_decode_opt_box_autoadd_telegram_login_status(arr[1]),
      error: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  ApiResultWeexAccountReconciliation dco_decode_api_result_weex_account_reconciliation(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ApiResultWeexAccountReconciliation(
      ok: dco_decode_bool(arr[0]),
      value: dco_decode_opt_box_autoadd_weex_account_reconciliation(arr[1]),
      error: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  ApiResultWeexMarketOrderAck dco_decode_api_result_weex_market_order_ack(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ApiResultWeexMarketOrderAck(
      ok: dco_decode_bool(arr[0]),
      value: dco_decode_opt_box_autoadd_weex_market_order_ack(arr[1]),
      error: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Action dco_decode_box_autoadd_action(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_action(raw);
  }

  @protected
  Direction dco_decode_box_autoadd_direction(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_direction(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  ManualScaleRequest dco_decode_box_autoadd_manual_scale_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_manual_scale_request(raw);
  }

  @protected
  ScaledOrder dco_decode_box_autoadd_scaled_order(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_scaled_order(raw);
  }

  @protected
  Size dco_decode_box_autoadd_size(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_size(raw);
  }

  @protected
  TelegramClientRequest dco_decode_box_autoadd_telegram_client_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_telegram_client_request(raw);
  }

  @protected
  TelegramLoginStatus dco_decode_box_autoadd_telegram_login_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_telegram_login_status(raw);
  }

  @protected
  WeexAccountReconciliation dco_decode_box_autoadd_weex_account_reconciliation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_weex_account_reconciliation(raw);
  }

  @protected
  WeexAccountRequest dco_decode_box_autoadd_weex_account_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_weex_account_request(raw);
  }

  @protected
  WeexMarketOrderAck dco_decode_box_autoadd_weex_market_order_ack(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_weex_market_order_ack(raw);
  }

  @protected
  WeexMarketOrderRequest dco_decode_box_autoadd_weex_market_order_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_weex_market_order_request(raw);
  }

  @protected
  ChartData dco_decode_chart_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ChartData(
      balance: dco_decode_list_series_point(arr[0]),
      equity: dco_decode_list_series_point(arr[1]),
      pnl: dco_decode_list_series_point(arr[2]),
    );
  }

  @protected
  Direction dco_decode_direction(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Direction.values[raw as int];
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SeriesPoint> dco_decode_list_series_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_series_point).toList();
  }

  @protected
  List<WeexExecutionSnapshot> dco_decode_list_weex_execution_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_weex_execution_snapshot).toList();
  }

  @protected
  ManualScaleRequest dco_decode_manual_scale_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6) throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ManualScaleRequest(
      amount: dco_decode_f_64(arr[0]),
      unit: dco_decode_manual_size_unit(arr[1]),
      masterBalanceUsd: dco_decode_f_64(arr[2]),
      myBalanceUsd: dco_decode_f_64(arr[3]),
      markPrice: dco_decode_f_64(arr[4]),
      qtyStep: dco_decode_f_64(arr[5]),
    );
  }

  @protected
  ManualSizeUnit dco_decode_manual_size_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ManualSizeUnit.values[raw as int];
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  Action? dco_decode_opt_box_autoadd_action(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_action(raw);
  }

  @protected
  Direction? dco_decode_opt_box_autoadd_direction(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_direction(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  ScaledOrder? dco_decode_opt_box_autoadd_scaled_order(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_scaled_order(raw);
  }

  @protected
  Size? dco_decode_opt_box_autoadd_size(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_size(raw);
  }

  @protected
  TelegramLoginStatus? dco_decode_opt_box_autoadd_telegram_login_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_telegram_login_status(raw);
  }

  @protected
  WeexAccountReconciliation? dco_decode_opt_box_autoadd_weex_account_reconciliation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_weex_account_reconciliation(raw);
  }

  @protected
  WeexMarketOrderAck? dco_decode_opt_box_autoadd_weex_market_order_ack(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_weex_market_order_ack(raw);
  }

  @protected
  PriceTick dco_decode_price_tick(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9) throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return PriceTick(
      symbol: dco_decode_String(arr[0]),
      price: dco_decode_opt_box_autoadd_f_64(arr[1]),
      bid: dco_decode_opt_box_autoadd_f_64(arr[2]),
      ask: dco_decode_opt_box_autoadd_f_64(arr[3]),
      source: dco_decode_String(arr[4]),
      eventTimeMs: dco_decode_opt_box_autoadd_i_64(arr[5]),
      receivedAtMs: dco_decode_i_64(arr[6]),
      ok: dco_decode_bool(arr[7]),
      error: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  ScaledOrder dco_decode_scaled_order(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ScaledOrder(
      ratio: dco_decode_f_64(arr[0]),
      qtyBtc: dco_decode_f_64(arr[1]),
      notionalUsd: dco_decode_f_64(arr[2]),
    );
  }

  @protected
  SeriesPoint dco_decode_series_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SeriesPoint(timestampMs: dco_decode_i_64(arr[0]), value: dco_decode_f_64(arr[1]));
  }

  @protected
  Size dco_decode_size(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return Size_Usd(dco_decode_f_64(raw[1]));
      case 1:
        return Size_Btc(dco_decode_f_64(raw[1]));
      case 2:
        return Size_Pct(dco_decode_f_64(raw[1]));
      case 3:
        return Size_FullClose();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  TelegramActionStatus dco_decode_telegram_action_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TelegramActionStatus.values[raw as int];
  }

  @protected
  TelegramClientRequest dco_decode_telegram_client_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6) throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return TelegramClientRequest(
      apiId: dco_decode_i_32(arr[0]),
      apiHash: dco_decode_String(arr[1]),
      phone: dco_decode_String(arr[2]),
      channelId: dco_decode_i_64(arr[3]),
      sessionPath: dco_decode_String(arr[4]),
      statePath: dco_decode_String(arr[5]),
    );
  }

  @protected
  TelegramLoginStatus dco_decode_telegram_login_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5) throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return TelegramLoginStatus(
      ok: dco_decode_bool(arr[0]),
      authorized: dco_decode_bool(arr[1]),
      needsCode: dco_decode_bool(arr[2]),
      needsPassword: dco_decode_bool(arr[3]),
      message: dco_decode_String(arr[4]),
    );
  }

  @protected
  TelegramMessageEvent dco_decode_telegram_message_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9) throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return TelegramMessageEvent(
      ok: dco_decode_bool(arr[0]),
      channelId: dco_decode_i_64(arr[1]),
      channelTitle: dco_decode_String(arr[2]),
      messageId: dco_decode_i_32(arr[3]),
      actionOrdinal: dco_decode_u_32(arr[4]),
      dedupKey: dco_decode_String(arr[5]),
      text: dco_decode_String(arr[6]),
      receivedAtMs: dco_decode_i_64(arr[7]),
      error: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WeexAccountBalance dco_decode_weex_account_balance(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6) throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return WeexAccountBalance(
      asset: dco_decode_String(arr[0]),
      walletBalance: dco_decode_f_64(arr[1]),
      availableBalance: dco_decode_f_64(arr[2]),
      unrealizedPnl: dco_decode_f_64(arr[3]),
      equity: dco_decode_f_64(arr[4]),
      usedMargin: dco_decode_f_64(arr[5]),
    );
  }

  @protected
  WeexAccountReconciliation dco_decode_weex_account_reconciliation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4) throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return WeexAccountReconciliation(
      balance: dco_decode_weex_account_balance(arr[0]),
      position: dco_decode_weex_position_snapshot(arr[1]),
      recentExecutions: dco_decode_list_weex_execution_snapshot(arr[2]),
      timestampMs: dco_decode_i_64(arr[3]),
    );
  }

  @protected
  WeexAccountRequest dco_decode_weex_account_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6) throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return WeexAccountRequest(
      apiKey: dco_decode_String(arr[0]),
      apiSecret: dco_decode_String(arr[1]),
      passphrase: dco_decode_String(arr[2]),
      symbol: dco_decode_String(arr[3]),
      baseUrl: dco_decode_String(arr[4]),
      recentLookbackMs: dco_decode_i_64(arr[5]),
    );
  }

  @protected
  WeexExecutionSnapshot dco_decode_weex_execution_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12) throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return WeexExecutionSnapshot(
      execId: dco_decode_String(arr[0]),
      orderId: dco_decode_String(arr[1]),
      side: dco_decode_String(arr[2]),
      positionSide: dco_decode_String(arr[3]),
      kind: dco_decode_String(arr[4]),
      direction: dco_decode_String(arr[5]),
      price: dco_decode_f_64(arr[6]),
      qtyBtc: dco_decode_f_64(arr[7]),
      notionalUsdt: dco_decode_f_64(arr[8]),
      realizedPnlUsdt: dco_decode_f_64(arr[9]),
      feeUsdt: dco_decode_f_64(arr[10]),
      timestampMs: dco_decode_i_64(arr[11]),
    );
  }

  @protected
  WeexMarketOrderAck dco_decode_weex_market_order_ack(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5) throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return WeexMarketOrderAck(
      orderId: dco_decode_String(arr[0]),
      clientOrderId: dco_decode_opt_String(arr[1]),
      success: dco_decode_bool(arr[2]),
      errorCode: dco_decode_String(arr[3]),
      errorMessage: dco_decode_String(arr[4]),
    );
  }

  @protected
  WeexMarketOrderRequest dco_decode_weex_market_order_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10) throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return WeexMarketOrderRequest(
      apiKey: dco_decode_String(arr[0]),
      apiSecret: dco_decode_String(arr[1]),
      passphrase: dco_decode_String(arr[2]),
      symbol: dco_decode_String(arr[3]),
      baseUrl: dco_decode_String(arr[4]),
      side: dco_decode_String(arr[5]),
      qtyBtc: dco_decode_f_64(arr[6]),
      reduceOnly: dco_decode_bool(arr[7]),
      clientOrderId: dco_decode_String(arr[8]),
      qtyStep: dco_decode_f_64(arr[9]),
    );
  }

  @protected
  WeexPositionSnapshot dco_decode_weex_position_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10) throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return WeexPositionSnapshot(
      symbol: dco_decode_String(arr[0]),
      direction: dco_decode_String(arr[1]),
      qtyBtc: dco_decode_f_64(arr[2]),
      entryPrice: dco_decode_f_64(arr[3]),
      markPrice: dco_decode_f_64(arr[4]),
      notionalUsdt: dco_decode_f_64(arr[5]),
      unrealizedPnlUsdt: dco_decode_f_64(arr[6]),
      leverage: dco_decode_f_64(arr[7]),
      liquidationPrice: dco_decode_opt_box_autoadd_f_64(arr[8]),
      updatedAtMs: dco_decode_i_64(arr[9]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<PriceTick> sse_decode_StreamSink_price_tick_Sse(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<TelegramMessageEvent> sse_decode_StreamSink_telegram_message_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Action sse_decode_action(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_action_kind(deserializer);
    var var_direction = sse_decode_opt_box_autoadd_direction(deserializer);
    var var_size = sse_decode_opt_box_autoadd_size(deserializer);
    var var_confidenceHigh = sse_decode_bool(deserializer);
    var var_needsApproval = sse_decode_bool(deserializer);
    var var_rawText = sse_decode_String(deserializer);
    return Action(
      kind: var_kind,
      direction: var_direction,
      size: var_size,
      confidenceHigh: var_confidenceHigh,
      needsApproval: var_needsApproval,
      rawText: var_rawText,
    );
  }

  @protected
  ActionKind sse_decode_action_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ActionKind.values[inner];
  }

  @protected
  ApiResultAction sse_decode_api_result_action(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_value = sse_decode_opt_box_autoadd_action(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return ApiResultAction(ok: var_ok, value: var_value, error: var_error);
  }

  @protected
  ApiResultScaledOrder sse_decode_api_result_scaled_order(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_value = sse_decode_opt_box_autoadd_scaled_order(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return ApiResultScaledOrder(ok: var_ok, value: var_value, error: var_error);
  }

  @protected
  ApiResultString sse_decode_api_result_string(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_value = sse_decode_opt_String(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return ApiResultString(ok: var_ok, value: var_value, error: var_error);
  }

  @protected
  ApiResultTelegramLoginStatus sse_decode_api_result_telegram_login_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_value = sse_decode_opt_box_autoadd_telegram_login_status(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return ApiResultTelegramLoginStatus(ok: var_ok, value: var_value, error: var_error);
  }

  @protected
  ApiResultWeexAccountReconciliation sse_decode_api_result_weex_account_reconciliation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_value = sse_decode_opt_box_autoadd_weex_account_reconciliation(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return ApiResultWeexAccountReconciliation(ok: var_ok, value: var_value, error: var_error);
  }

  @protected
  ApiResultWeexMarketOrderAck sse_decode_api_result_weex_market_order_ack(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_value = sse_decode_opt_box_autoadd_weex_market_order_ack(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return ApiResultWeexMarketOrderAck(ok: var_ok, value: var_value, error: var_error);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Action sse_decode_box_autoadd_action(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_action(deserializer));
  }

  @protected
  Direction sse_decode_box_autoadd_direction(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_direction(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  ManualScaleRequest sse_decode_box_autoadd_manual_scale_request(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_manual_scale_request(deserializer));
  }

  @protected
  ScaledOrder sse_decode_box_autoadd_scaled_order(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_scaled_order(deserializer));
  }

  @protected
  Size sse_decode_box_autoadd_size(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_size(deserializer));
  }

  @protected
  TelegramClientRequest sse_decode_box_autoadd_telegram_client_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_telegram_client_request(deserializer));
  }

  @protected
  TelegramLoginStatus sse_decode_box_autoadd_telegram_login_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_telegram_login_status(deserializer));
  }

  @protected
  WeexAccountReconciliation sse_decode_box_autoadd_weex_account_reconciliation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_weex_account_reconciliation(deserializer));
  }

  @protected
  WeexAccountRequest sse_decode_box_autoadd_weex_account_request(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_weex_account_request(deserializer));
  }

  @protected
  WeexMarketOrderAck sse_decode_box_autoadd_weex_market_order_ack(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_weex_market_order_ack(deserializer));
  }

  @protected
  WeexMarketOrderRequest sse_decode_box_autoadd_weex_market_order_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_weex_market_order_request(deserializer));
  }

  @protected
  ChartData sse_decode_chart_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_balance = sse_decode_list_series_point(deserializer);
    var var_equity = sse_decode_list_series_point(deserializer);
    var var_pnl = sse_decode_list_series_point(deserializer);
    return ChartData(balance: var_balance, equity: var_equity, pnl: var_pnl);
  }

  @protected
  Direction sse_decode_direction(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Direction.values[inner];
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SeriesPoint> sse_decode_list_series_point(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SeriesPoint>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_series_point(deserializer));
    }
    return ans_;
  }

  @protected
  List<WeexExecutionSnapshot> sse_decode_list_weex_execution_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <WeexExecutionSnapshot>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_weex_execution_snapshot(deserializer));
    }
    return ans_;
  }

  @protected
  ManualScaleRequest sse_decode_manual_scale_request(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_amount = sse_decode_f_64(deserializer);
    var var_unit = sse_decode_manual_size_unit(deserializer);
    var var_masterBalanceUsd = sse_decode_f_64(deserializer);
    var var_myBalanceUsd = sse_decode_f_64(deserializer);
    var var_markPrice = sse_decode_f_64(deserializer);
    var var_qtyStep = sse_decode_f_64(deserializer);
    return ManualScaleRequest(
      amount: var_amount,
      unit: var_unit,
      masterBalanceUsd: var_masterBalanceUsd,
      myBalanceUsd: var_myBalanceUsd,
      markPrice: var_markPrice,
      qtyStep: var_qtyStep,
    );
  }

  @protected
  ManualSizeUnit sse_decode_manual_size_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ManualSizeUnit.values[inner];
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Action? sse_decode_opt_box_autoadd_action(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_action(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Direction? sse_decode_opt_box_autoadd_direction(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_direction(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ScaledOrder? sse_decode_opt_box_autoadd_scaled_order(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_scaled_order(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Size? sse_decode_opt_box_autoadd_size(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_size(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TelegramLoginStatus? sse_decode_opt_box_autoadd_telegram_login_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_telegram_login_status(deserializer));
    } else {
      return null;
    }
  }

  @protected
  WeexAccountReconciliation? sse_decode_opt_box_autoadd_weex_account_reconciliation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_weex_account_reconciliation(deserializer));
    } else {
      return null;
    }
  }

  @protected
  WeexMarketOrderAck? sse_decode_opt_box_autoadd_weex_market_order_ack(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_weex_market_order_ack(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PriceTick sse_decode_price_tick(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_symbol = sse_decode_String(deserializer);
    var var_price = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_bid = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_ask = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_source = sse_decode_String(deserializer);
    var var_eventTimeMs = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_receivedAtMs = sse_decode_i_64(deserializer);
    var var_ok = sse_decode_bool(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return PriceTick(
      symbol: var_symbol,
      price: var_price,
      bid: var_bid,
      ask: var_ask,
      source: var_source,
      eventTimeMs: var_eventTimeMs,
      receivedAtMs: var_receivedAtMs,
      ok: var_ok,
      error: var_error,
    );
  }

  @protected
  ScaledOrder sse_decode_scaled_order(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ratio = sse_decode_f_64(deserializer);
    var var_qtyBtc = sse_decode_f_64(deserializer);
    var var_notionalUsd = sse_decode_f_64(deserializer);
    return ScaledOrder(ratio: var_ratio, qtyBtc: var_qtyBtc, notionalUsd: var_notionalUsd);
  }

  @protected
  SeriesPoint sse_decode_series_point(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timestampMs = sse_decode_i_64(deserializer);
    var var_value = sse_decode_f_64(deserializer);
    return SeriesPoint(timestampMs: var_timestampMs, value: var_value);
  }

  @protected
  Size sse_decode_size(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_f_64(deserializer);
        return Size_Usd(var_field0);
      case 1:
        var var_field0 = sse_decode_f_64(deserializer);
        return Size_Btc(var_field0);
      case 2:
        var var_field0 = sse_decode_f_64(deserializer);
        return Size_Pct(var_field0);
      case 3:
        return Size_FullClose();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  TelegramActionStatus sse_decode_telegram_action_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TelegramActionStatus.values[inner];
  }

  @protected
  TelegramClientRequest sse_decode_telegram_client_request(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_apiId = sse_decode_i_32(deserializer);
    var var_apiHash = sse_decode_String(deserializer);
    var var_phone = sse_decode_String(deserializer);
    var var_channelId = sse_decode_i_64(deserializer);
    var var_sessionPath = sse_decode_String(deserializer);
    var var_statePath = sse_decode_String(deserializer);
    return TelegramClientRequest(
      apiId: var_apiId,
      apiHash: var_apiHash,
      phone: var_phone,
      channelId: var_channelId,
      sessionPath: var_sessionPath,
      statePath: var_statePath,
    );
  }

  @protected
  TelegramLoginStatus sse_decode_telegram_login_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_authorized = sse_decode_bool(deserializer);
    var var_needsCode = sse_decode_bool(deserializer);
    var var_needsPassword = sse_decode_bool(deserializer);
    var var_message = sse_decode_String(deserializer);
    return TelegramLoginStatus(
      ok: var_ok,
      authorized: var_authorized,
      needsCode: var_needsCode,
      needsPassword: var_needsPassword,
      message: var_message,
    );
  }

  @protected
  TelegramMessageEvent sse_decode_telegram_message_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_channelId = sse_decode_i_64(deserializer);
    var var_channelTitle = sse_decode_String(deserializer);
    var var_messageId = sse_decode_i_32(deserializer);
    var var_actionOrdinal = sse_decode_u_32(deserializer);
    var var_dedupKey = sse_decode_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_receivedAtMs = sse_decode_i_64(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return TelegramMessageEvent(
      ok: var_ok,
      channelId: var_channelId,
      channelTitle: var_channelTitle,
      messageId: var_messageId,
      actionOrdinal: var_actionOrdinal,
      dedupKey: var_dedupKey,
      text: var_text,
      receivedAtMs: var_receivedAtMs,
      error: var_error,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WeexAccountBalance sse_decode_weex_account_balance(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_asset = sse_decode_String(deserializer);
    var var_walletBalance = sse_decode_f_64(deserializer);
    var var_availableBalance = sse_decode_f_64(deserializer);
    var var_unrealizedPnl = sse_decode_f_64(deserializer);
    var var_equity = sse_decode_f_64(deserializer);
    var var_usedMargin = sse_decode_f_64(deserializer);
    return WeexAccountBalance(
      asset: var_asset,
      walletBalance: var_walletBalance,
      availableBalance: var_availableBalance,
      unrealizedPnl: var_unrealizedPnl,
      equity: var_equity,
      usedMargin: var_usedMargin,
    );
  }

  @protected
  WeexAccountReconciliation sse_decode_weex_account_reconciliation(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_balance = sse_decode_weex_account_balance(deserializer);
    var var_position = sse_decode_weex_position_snapshot(deserializer);
    var var_recentExecutions = sse_decode_list_weex_execution_snapshot(deserializer);
    var var_timestampMs = sse_decode_i_64(deserializer);
    return WeexAccountReconciliation(
      balance: var_balance,
      position: var_position,
      recentExecutions: var_recentExecutions,
      timestampMs: var_timestampMs,
    );
  }

  @protected
  WeexAccountRequest sse_decode_weex_account_request(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_apiKey = sse_decode_String(deserializer);
    var var_apiSecret = sse_decode_String(deserializer);
    var var_passphrase = sse_decode_String(deserializer);
    var var_symbol = sse_decode_String(deserializer);
    var var_baseUrl = sse_decode_String(deserializer);
    var var_recentLookbackMs = sse_decode_i_64(deserializer);
    return WeexAccountRequest(
      apiKey: var_apiKey,
      apiSecret: var_apiSecret,
      passphrase: var_passphrase,
      symbol: var_symbol,
      baseUrl: var_baseUrl,
      recentLookbackMs: var_recentLookbackMs,
    );
  }

  @protected
  WeexExecutionSnapshot sse_decode_weex_execution_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_execId = sse_decode_String(deserializer);
    var var_orderId = sse_decode_String(deserializer);
    var var_side = sse_decode_String(deserializer);
    var var_positionSide = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_direction = sse_decode_String(deserializer);
    var var_price = sse_decode_f_64(deserializer);
    var var_qtyBtc = sse_decode_f_64(deserializer);
    var var_notionalUsdt = sse_decode_f_64(deserializer);
    var var_realizedPnlUsdt = sse_decode_f_64(deserializer);
    var var_feeUsdt = sse_decode_f_64(deserializer);
    var var_timestampMs = sse_decode_i_64(deserializer);
    return WeexExecutionSnapshot(
      execId: var_execId,
      orderId: var_orderId,
      side: var_side,
      positionSide: var_positionSide,
      kind: var_kind,
      direction: var_direction,
      price: var_price,
      qtyBtc: var_qtyBtc,
      notionalUsdt: var_notionalUsdt,
      realizedPnlUsdt: var_realizedPnlUsdt,
      feeUsdt: var_feeUsdt,
      timestampMs: var_timestampMs,
    );
  }

  @protected
  WeexMarketOrderAck sse_decode_weex_market_order_ack(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_orderId = sse_decode_String(deserializer);
    var var_clientOrderId = sse_decode_opt_String(deserializer);
    var var_success = sse_decode_bool(deserializer);
    var var_errorCode = sse_decode_String(deserializer);
    var var_errorMessage = sse_decode_String(deserializer);
    return WeexMarketOrderAck(
      orderId: var_orderId,
      clientOrderId: var_clientOrderId,
      success: var_success,
      errorCode: var_errorCode,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  WeexMarketOrderRequest sse_decode_weex_market_order_request(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_apiKey = sse_decode_String(deserializer);
    var var_apiSecret = sse_decode_String(deserializer);
    var var_passphrase = sse_decode_String(deserializer);
    var var_symbol = sse_decode_String(deserializer);
    var var_baseUrl = sse_decode_String(deserializer);
    var var_side = sse_decode_String(deserializer);
    var var_qtyBtc = sse_decode_f_64(deserializer);
    var var_reduceOnly = sse_decode_bool(deserializer);
    var var_clientOrderId = sse_decode_String(deserializer);
    var var_qtyStep = sse_decode_f_64(deserializer);
    return WeexMarketOrderRequest(
      apiKey: var_apiKey,
      apiSecret: var_apiSecret,
      passphrase: var_passphrase,
      symbol: var_symbol,
      baseUrl: var_baseUrl,
      side: var_side,
      qtyBtc: var_qtyBtc,
      reduceOnly: var_reduceOnly,
      clientOrderId: var_clientOrderId,
      qtyStep: var_qtyStep,
    );
  }

  @protected
  WeexPositionSnapshot sse_decode_weex_position_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_symbol = sse_decode_String(deserializer);
    var var_direction = sse_decode_String(deserializer);
    var var_qtyBtc = sse_decode_f_64(deserializer);
    var var_entryPrice = sse_decode_f_64(deserializer);
    var var_markPrice = sse_decode_f_64(deserializer);
    var var_notionalUsdt = sse_decode_f_64(deserializer);
    var var_unrealizedPnlUsdt = sse_decode_f_64(deserializer);
    var var_leverage = sse_decode_f_64(deserializer);
    var var_liquidationPrice = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_updatedAtMs = sse_decode_i_64(deserializer);
    return WeexPositionSnapshot(
      symbol: var_symbol,
      direction: var_direction,
      qtyBtc: var_qtyBtc,
      entryPrice: var_entryPrice,
      markPrice: var_markPrice,
      notionalUsdt: var_notionalUsdt,
      unrealizedPnlUsdt: var_unrealizedPnlUsdt,
      leverage: var_leverage,
      liquidationPrice: var_liquidationPrice,
      updatedAtMs: var_updatedAtMs,
    );
  }

  @protected
  void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_price_tick_Sse(
    RustStreamSink<PriceTick> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_price_tick,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_telegram_message_event_Sse(
    RustStreamSink<TelegramMessageEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_telegram_message_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_action(Action self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_action_kind(self.kind, serializer);
    sse_encode_opt_box_autoadd_direction(self.direction, serializer);
    sse_encode_opt_box_autoadd_size(self.size, serializer);
    sse_encode_bool(self.confidenceHigh, serializer);
    sse_encode_bool(self.needsApproval, serializer);
    sse_encode_String(self.rawText, serializer);
  }

  @protected
  void sse_encode_action_kind(ActionKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_api_result_action(ApiResultAction self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_opt_box_autoadd_action(self.value, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_api_result_scaled_order(ApiResultScaledOrder self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_opt_box_autoadd_scaled_order(self.value, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_api_result_string(ApiResultString self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_opt_String(self.value, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_api_result_telegram_login_status(
    ApiResultTelegramLoginStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_opt_box_autoadd_telegram_login_status(self.value, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_api_result_weex_account_reconciliation(
    ApiResultWeexAccountReconciliation self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_opt_box_autoadd_weex_account_reconciliation(self.value, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_api_result_weex_market_order_ack(
    ApiResultWeexMarketOrderAck self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_opt_box_autoadd_weex_market_order_ack(self.value, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_action(Action self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_action(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_direction(Direction self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_direction(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_manual_scale_request(
    ManualScaleRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_manual_scale_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_scaled_order(ScaledOrder self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_scaled_order(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_size(Size self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_size(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_telegram_client_request(
    TelegramClientRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_telegram_client_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_telegram_login_status(
    TelegramLoginStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_telegram_login_status(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_weex_account_reconciliation(
    WeexAccountReconciliation self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_weex_account_reconciliation(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_weex_account_request(
    WeexAccountRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_weex_account_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_weex_market_order_ack(
    WeexMarketOrderAck self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_weex_market_order_ack(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_weex_market_order_request(
    WeexMarketOrderRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_weex_market_order_request(self, serializer);
  }

  @protected
  void sse_encode_chart_data(ChartData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_series_point(self.balance, serializer);
    sse_encode_list_series_point(self.equity, serializer);
    sse_encode_list_series_point(self.pnl, serializer);
  }

  @protected
  void sse_encode_direction(Direction self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_series_point(List<SeriesPoint> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_series_point(item, serializer);
    }
  }

  @protected
  void sse_encode_list_weex_execution_snapshot(
    List<WeexExecutionSnapshot> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_weex_execution_snapshot(item, serializer);
    }
  }

  @protected
  void sse_encode_manual_scale_request(ManualScaleRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.amount, serializer);
    sse_encode_manual_size_unit(self.unit, serializer);
    sse_encode_f_64(self.masterBalanceUsd, serializer);
    sse_encode_f_64(self.myBalanceUsd, serializer);
    sse_encode_f_64(self.markPrice, serializer);
    sse_encode_f_64(self.qtyStep, serializer);
  }

  @protected
  void sse_encode_manual_size_unit(ManualSizeUnit self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_action(Action? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_action(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_direction(Direction? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_direction(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(PlatformInt64? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_scaled_order(ScaledOrder? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_scaled_order(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_size(Size? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_size(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_telegram_login_status(
    TelegramLoginStatus? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_telegram_login_status(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_weex_account_reconciliation(
    WeexAccountReconciliation? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_weex_account_reconciliation(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_weex_market_order_ack(
    WeexMarketOrderAck? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_weex_market_order_ack(self, serializer);
    }
  }

  @protected
  void sse_encode_price_tick(PriceTick self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.symbol, serializer);
    sse_encode_opt_box_autoadd_f_64(self.price, serializer);
    sse_encode_opt_box_autoadd_f_64(self.bid, serializer);
    sse_encode_opt_box_autoadd_f_64(self.ask, serializer);
    sse_encode_String(self.source, serializer);
    sse_encode_opt_box_autoadd_i_64(self.eventTimeMs, serializer);
    sse_encode_i_64(self.receivedAtMs, serializer);
    sse_encode_bool(self.ok, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_scaled_order(ScaledOrder self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.ratio, serializer);
    sse_encode_f_64(self.qtyBtc, serializer);
    sse_encode_f_64(self.notionalUsd, serializer);
  }

  @protected
  void sse_encode_series_point(SeriesPoint self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.timestampMs, serializer);
    sse_encode_f_64(self.value, serializer);
  }

  @protected
  void sse_encode_size(Size self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case Size_Usd(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_f_64(field0, serializer);
      case Size_Btc(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_f_64(field0, serializer);
      case Size_Pct(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_f_64(field0, serializer);
      case Size_FullClose():
        sse_encode_i_32(3, serializer);
    }
  }

  @protected
  void sse_encode_telegram_action_status(TelegramActionStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_telegram_client_request(TelegramClientRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.apiId, serializer);
    sse_encode_String(self.apiHash, serializer);
    sse_encode_String(self.phone, serializer);
    sse_encode_i_64(self.channelId, serializer);
    sse_encode_String(self.sessionPath, serializer);
    sse_encode_String(self.statePath, serializer);
  }

  @protected
  void sse_encode_telegram_login_status(TelegramLoginStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_bool(self.authorized, serializer);
    sse_encode_bool(self.needsCode, serializer);
    sse_encode_bool(self.needsPassword, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_telegram_message_event(TelegramMessageEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_i_64(self.channelId, serializer);
    sse_encode_String(self.channelTitle, serializer);
    sse_encode_i_32(self.messageId, serializer);
    sse_encode_u_32(self.actionOrdinal, serializer);
    sse_encode_String(self.dedupKey, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_i_64(self.receivedAtMs, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_weex_account_balance(WeexAccountBalance self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.asset, serializer);
    sse_encode_f_64(self.walletBalance, serializer);
    sse_encode_f_64(self.availableBalance, serializer);
    sse_encode_f_64(self.unrealizedPnl, serializer);
    sse_encode_f_64(self.equity, serializer);
    sse_encode_f_64(self.usedMargin, serializer);
  }

  @protected
  void sse_encode_weex_account_reconciliation(
    WeexAccountReconciliation self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_weex_account_balance(self.balance, serializer);
    sse_encode_weex_position_snapshot(self.position, serializer);
    sse_encode_list_weex_execution_snapshot(self.recentExecutions, serializer);
    sse_encode_i_64(self.timestampMs, serializer);
  }

  @protected
  void sse_encode_weex_account_request(WeexAccountRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.apiKey, serializer);
    sse_encode_String(self.apiSecret, serializer);
    sse_encode_String(self.passphrase, serializer);
    sse_encode_String(self.symbol, serializer);
    sse_encode_String(self.baseUrl, serializer);
    sse_encode_i_64(self.recentLookbackMs, serializer);
  }

  @protected
  void sse_encode_weex_execution_snapshot(WeexExecutionSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.execId, serializer);
    sse_encode_String(self.orderId, serializer);
    sse_encode_String(self.side, serializer);
    sse_encode_String(self.positionSide, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.direction, serializer);
    sse_encode_f_64(self.price, serializer);
    sse_encode_f_64(self.qtyBtc, serializer);
    sse_encode_f_64(self.notionalUsdt, serializer);
    sse_encode_f_64(self.realizedPnlUsdt, serializer);
    sse_encode_f_64(self.feeUsdt, serializer);
    sse_encode_i_64(self.timestampMs, serializer);
  }

  @protected
  void sse_encode_weex_market_order_ack(WeexMarketOrderAck self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.orderId, serializer);
    sse_encode_opt_String(self.clientOrderId, serializer);
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.errorCode, serializer);
    sse_encode_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_weex_market_order_request(WeexMarketOrderRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.apiKey, serializer);
    sse_encode_String(self.apiSecret, serializer);
    sse_encode_String(self.passphrase, serializer);
    sse_encode_String(self.symbol, serializer);
    sse_encode_String(self.baseUrl, serializer);
    sse_encode_String(self.side, serializer);
    sse_encode_f_64(self.qtyBtc, serializer);
    sse_encode_bool(self.reduceOnly, serializer);
    sse_encode_String(self.clientOrderId, serializer);
    sse_encode_f_64(self.qtyStep, serializer);
  }

  @protected
  void sse_encode_weex_position_snapshot(WeexPositionSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.symbol, serializer);
    sse_encode_String(self.direction, serializer);
    sse_encode_f_64(self.qtyBtc, serializer);
    sse_encode_f_64(self.entryPrice, serializer);
    sse_encode_f_64(self.markPrice, serializer);
    sse_encode_f_64(self.notionalUsdt, serializer);
    sse_encode_f_64(self.unrealizedPnlUsdt, serializer);
    sse_encode_f_64(self.leverage, serializer);
    sse_encode_opt_box_autoadd_f_64(self.liquidationPrice, serializer);
    sse_encode_i_64(self.updatedAtMs, serializer);
  }
}
