// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'interpreter.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'scaling.dart';
import 'weex.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<PriceTick> dco_decode_StreamSink_price_tick_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Action dco_decode_action(dynamic raw);

  @protected
  ActionKind dco_decode_action_kind(dynamic raw);

  @protected
  ApiResultAction dco_decode_api_result_action(dynamic raw);

  @protected
  ApiResultScaledOrder dco_decode_api_result_scaled_order(dynamic raw);

  @protected
  ApiResultString dco_decode_api_result_string(dynamic raw);

  @protected
  ApiResultWeexAccountReconciliation
  dco_decode_api_result_weex_account_reconciliation(dynamic raw);

  @protected
  ApiResultWeexMarketOrderAck dco_decode_api_result_weex_market_order_ack(
    dynamic raw,
  );

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Action dco_decode_box_autoadd_action(dynamic raw);

  @protected
  Direction dco_decode_box_autoadd_direction(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  ManualScaleRequest dco_decode_box_autoadd_manual_scale_request(dynamic raw);

  @protected
  ScaledOrder dco_decode_box_autoadd_scaled_order(dynamic raw);

  @protected
  Size dco_decode_box_autoadd_size(dynamic raw);

  @protected
  WeexAccountReconciliation dco_decode_box_autoadd_weex_account_reconciliation(
    dynamic raw,
  );

  @protected
  WeexAccountRequest dco_decode_box_autoadd_weex_account_request(dynamic raw);

  @protected
  WeexMarketOrderAck dco_decode_box_autoadd_weex_market_order_ack(dynamic raw);

  @protected
  WeexMarketOrderRequest dco_decode_box_autoadd_weex_market_order_request(
    dynamic raw,
  );

  @protected
  ChartData dco_decode_chart_data(dynamic raw);

  @protected
  Direction dco_decode_direction(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SeriesPoint> dco_decode_list_series_point(dynamic raw);

  @protected
  List<WeexExecutionSnapshot> dco_decode_list_weex_execution_snapshot(
    dynamic raw,
  );

  @protected
  ManualScaleRequest dco_decode_manual_scale_request(dynamic raw);

  @protected
  ManualSizeUnit dco_decode_manual_size_unit(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  Action? dco_decode_opt_box_autoadd_action(dynamic raw);

  @protected
  Direction? dco_decode_opt_box_autoadd_direction(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  ScaledOrder? dco_decode_opt_box_autoadd_scaled_order(dynamic raw);

  @protected
  Size? dco_decode_opt_box_autoadd_size(dynamic raw);

  @protected
  WeexAccountReconciliation?
  dco_decode_opt_box_autoadd_weex_account_reconciliation(dynamic raw);

  @protected
  WeexMarketOrderAck? dco_decode_opt_box_autoadd_weex_market_order_ack(
    dynamic raw,
  );

  @protected
  PriceTick dco_decode_price_tick(dynamic raw);

  @protected
  ScaledOrder dco_decode_scaled_order(dynamic raw);

  @protected
  SeriesPoint dco_decode_series_point(dynamic raw);

  @protected
  Size dco_decode_size(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WeexAccountBalance dco_decode_weex_account_balance(dynamic raw);

  @protected
  WeexAccountReconciliation dco_decode_weex_account_reconciliation(dynamic raw);

  @protected
  WeexAccountRequest dco_decode_weex_account_request(dynamic raw);

  @protected
  WeexExecutionSnapshot dco_decode_weex_execution_snapshot(dynamic raw);

  @protected
  WeexMarketOrderAck dco_decode_weex_market_order_ack(dynamic raw);

  @protected
  WeexMarketOrderRequest dco_decode_weex_market_order_request(dynamic raw);

  @protected
  WeexPositionSnapshot dco_decode_weex_position_snapshot(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<PriceTick> sse_decode_StreamSink_price_tick_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  Action sse_decode_action(SseDeserializer deserializer);

  @protected
  ActionKind sse_decode_action_kind(SseDeserializer deserializer);

  @protected
  ApiResultAction sse_decode_api_result_action(SseDeserializer deserializer);

  @protected
  ApiResultScaledOrder sse_decode_api_result_scaled_order(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultString sse_decode_api_result_string(SseDeserializer deserializer);

  @protected
  ApiResultWeexAccountReconciliation
  sse_decode_api_result_weex_account_reconciliation(
    SseDeserializer deserializer,
  );

  @protected
  ApiResultWeexMarketOrderAck sse_decode_api_result_weex_market_order_ack(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Action sse_decode_box_autoadd_action(SseDeserializer deserializer);

  @protected
  Direction sse_decode_box_autoadd_direction(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ManualScaleRequest sse_decode_box_autoadd_manual_scale_request(
    SseDeserializer deserializer,
  );

  @protected
  ScaledOrder sse_decode_box_autoadd_scaled_order(SseDeserializer deserializer);

  @protected
  Size sse_decode_box_autoadd_size(SseDeserializer deserializer);

  @protected
  WeexAccountReconciliation sse_decode_box_autoadd_weex_account_reconciliation(
    SseDeserializer deserializer,
  );

  @protected
  WeexAccountRequest sse_decode_box_autoadd_weex_account_request(
    SseDeserializer deserializer,
  );

  @protected
  WeexMarketOrderAck sse_decode_box_autoadd_weex_market_order_ack(
    SseDeserializer deserializer,
  );

  @protected
  WeexMarketOrderRequest sse_decode_box_autoadd_weex_market_order_request(
    SseDeserializer deserializer,
  );

  @protected
  ChartData sse_decode_chart_data(SseDeserializer deserializer);

  @protected
  Direction sse_decode_direction(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SeriesPoint> sse_decode_list_series_point(SseDeserializer deserializer);

  @protected
  List<WeexExecutionSnapshot> sse_decode_list_weex_execution_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  ManualScaleRequest sse_decode_manual_scale_request(
    SseDeserializer deserializer,
  );

  @protected
  ManualSizeUnit sse_decode_manual_size_unit(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  Action? sse_decode_opt_box_autoadd_action(SseDeserializer deserializer);

  @protected
  Direction? sse_decode_opt_box_autoadd_direction(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ScaledOrder? sse_decode_opt_box_autoadd_scaled_order(
    SseDeserializer deserializer,
  );

  @protected
  Size? sse_decode_opt_box_autoadd_size(SseDeserializer deserializer);

  @protected
  WeexAccountReconciliation?
  sse_decode_opt_box_autoadd_weex_account_reconciliation(
    SseDeserializer deserializer,
  );

  @protected
  WeexMarketOrderAck? sse_decode_opt_box_autoadd_weex_market_order_ack(
    SseDeserializer deserializer,
  );

  @protected
  PriceTick sse_decode_price_tick(SseDeserializer deserializer);

  @protected
  ScaledOrder sse_decode_scaled_order(SseDeserializer deserializer);

  @protected
  SeriesPoint sse_decode_series_point(SseDeserializer deserializer);

  @protected
  Size sse_decode_size(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WeexAccountBalance sse_decode_weex_account_balance(
    SseDeserializer deserializer,
  );

  @protected
  WeexAccountReconciliation sse_decode_weex_account_reconciliation(
    SseDeserializer deserializer,
  );

  @protected
  WeexAccountRequest sse_decode_weex_account_request(
    SseDeserializer deserializer,
  );

  @protected
  WeexExecutionSnapshot sse_decode_weex_execution_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  WeexMarketOrderAck sse_decode_weex_market_order_ack(
    SseDeserializer deserializer,
  );

  @protected
  WeexMarketOrderRequest sse_decode_weex_market_order_request(
    SseDeserializer deserializer,
  );

  @protected
  WeexPositionSnapshot sse_decode_weex_position_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_price_tick_Sse(
    RustStreamSink<PriceTick> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_action(Action self, SseSerializer serializer);

  @protected
  void sse_encode_action_kind(ActionKind self, SseSerializer serializer);

  @protected
  void sse_encode_api_result_action(
    ApiResultAction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_result_scaled_order(
    ApiResultScaledOrder self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_result_string(
    ApiResultString self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_result_weex_account_reconciliation(
    ApiResultWeexAccountReconciliation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_result_weex_market_order_ack(
    ApiResultWeexMarketOrderAck self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_action(Action self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_direction(
    Direction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_manual_scale_request(
    ManualScaleRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_scaled_order(
    ScaledOrder self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_size(Size self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_weex_account_reconciliation(
    WeexAccountReconciliation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_weex_account_request(
    WeexAccountRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_weex_market_order_ack(
    WeexMarketOrderAck self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_weex_market_order_request(
    WeexMarketOrderRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chart_data(ChartData self, SseSerializer serializer);

  @protected
  void sse_encode_direction(Direction self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_series_point(
    List<SeriesPoint> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_weex_execution_snapshot(
    List<WeexExecutionSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_manual_scale_request(
    ManualScaleRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_manual_size_unit(
    ManualSizeUnit self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_action(
    Action? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_direction(
    Direction? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_scaled_order(
    ScaledOrder? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_size(Size? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_weex_account_reconciliation(
    WeexAccountReconciliation? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_weex_market_order_ack(
    WeexMarketOrderAck? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_price_tick(PriceTick self, SseSerializer serializer);

  @protected
  void sse_encode_scaled_order(ScaledOrder self, SseSerializer serializer);

  @protected
  void sse_encode_series_point(SeriesPoint self, SseSerializer serializer);

  @protected
  void sse_encode_size(Size self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_weex_account_balance(
    WeexAccountBalance self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_weex_account_reconciliation(
    WeexAccountReconciliation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_weex_account_request(
    WeexAccountRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_weex_execution_snapshot(
    WeexExecutionSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_weex_market_order_ack(
    WeexMarketOrderAck self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_weex_market_order_request(
    WeexMarketOrderRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_weex_position_snapshot(
    WeexPositionSnapshot self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
