// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'interpreter.freezed.dart';

class Action {
  final ActionKind kind;
  final Direction? direction;
  final Size? size;
  final double? triggerPrice;
  final bool confidenceHigh;
  final bool needsApproval;
  final String rawText;

  const Action({
    required this.kind,
    this.direction,
    this.size,
    this.triggerPrice,
    required this.confidenceHigh,
    required this.needsApproval,
    required this.rawText,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      direction.hashCode ^
      size.hashCode ^
      triggerPrice.hashCode ^
      confidenceHigh.hashCode ^
      needsApproval.hashCode ^
      rawText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Action &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          direction == other.direction &&
          size == other.size &&
          triggerPrice == other.triggerPrice &&
          confidenceHigh == other.confidenceHigh &&
          needsApproval == other.needsApproval &&
          rawText == other.rawText;
}

enum ActionKind { enter, add, reduce, close, ignore }

enum Direction { long, short }

@freezed
sealed class Size with _$Size {
  const Size._();

  const factory Size.usd(double field0) = Size_Usd;
  const factory Size.btc(double field0) = Size_Btc;
  const factory Size.pct(double field0) = Size_Pct;
  const factory Size.fullClose() = Size_FullClose;
}
