// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A limit expressed either as an absolute USD amount or as a percentage of
/// account balance.
///
/// The percentage form exists because this app is used for balance-scaling
/// challenges: a fixed "$500 per order" that fits a $7k account strangles the
/// same strategy at $500k, and the failure is silent. "15%" holds across two
/// orders of magnitude without ever being edited.
///
/// `value <= 0` means the limit is off, whichever form it is in.
class Limit {
  final double value;

  /// True when [`value`] is a percentage of account balance rather than USD.
  final bool percent;

  const Limit({required this.value, required this.percent});

  @override
  int get hashCode => value.hashCode ^ percent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Limit &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          percent == other.percent;
}

/// Live account facts the gate compares limits against.
class RiskContext {
  /// Latest mark price, used to turn quantities into notional.
  final double referencePrice;

  /// Notional of the currently open position, 0 when flat.
  final double openPositionNotionalUsd;

  /// Account leverage currently in effect.
  final double leverage;

  /// Realized PnL since midnight UTC. Negative is a loss.
  final double realizedPnlTodayUsd;

  /// Account balance, the basis for percentage limits.
  final double accountBalanceUsd;

  const RiskContext({
    required this.referencePrice,
    required this.openPositionNotionalUsd,
    required this.leverage,
    required this.realizedPnlTodayUsd,
    required this.accountBalanceUsd,
  });

  @override
  int get hashCode =>
      referencePrice.hashCode ^
      openPositionNotionalUsd.hashCode ^
      leverage.hashCode ^
      realizedPnlTodayUsd.hashCode ^
      accountBalanceUsd.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RiskContext &&
          runtimeType == other.runtimeType &&
          referencePrice == other.referencePrice &&
          openPositionNotionalUsd == other.openPositionNotionalUsd &&
          leverage == other.leverage &&
          realizedPnlTodayUsd == other.realizedPnlTodayUsd &&
          accountBalanceUsd == other.accountBalanceUsd;
}

class RiskLimits {
  /// Blocks every new opening order. Reduce-only still passes.
  final bool killSwitch;

  /// Largest notional (qty x reference price) a single opening order may have.
  final Limit maxOrderNotional;

  /// Largest quantity a single opening order may have.
  final double maxOrderQtyBtc;

  /// Largest total position notional allowed after the order fills.
  final Limit maxPositionNotional;

  /// Symbols that may be traded at all. Empty means "no allowlist configured".
  final List<String> symbolAllowlist;

  /// Largest account leverage allowed when opening.
  final double maxLeverage;

  /// Stops opening once realized loss today reaches this much.
  final Limit dailyLoss;

  /// Rejects signals older than this. Guards against replayed backlog after
  /// a long disconnect.
  final PlatformInt64 maxSignalAgeSecs;

  const RiskLimits({
    required this.killSwitch,
    required this.maxOrderNotional,
    required this.maxOrderQtyBtc,
    required this.maxPositionNotional,
    required this.symbolAllowlist,
    required this.maxLeverage,
    required this.dailyLoss,
    required this.maxSignalAgeSecs,
  });

  @override
  int get hashCode =>
      killSwitch.hashCode ^
      maxOrderNotional.hashCode ^
      maxOrderQtyBtc.hashCode ^
      maxPositionNotional.hashCode ^
      symbolAllowlist.hashCode ^
      maxLeverage.hashCode ^
      dailyLoss.hashCode ^
      maxSignalAgeSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RiskLimits &&
          runtimeType == other.runtimeType &&
          killSwitch == other.killSwitch &&
          maxOrderNotional == other.maxOrderNotional &&
          maxOrderQtyBtc == other.maxOrderQtyBtc &&
          maxPositionNotional == other.maxPositionNotional &&
          symbolAllowlist == other.symbolAllowlist &&
          maxLeverage == other.maxLeverage &&
          dailyLoss == other.dailyLoss &&
          maxSignalAgeSecs == other.maxSignalAgeSecs;
}
