// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ScaledOrder {
  final double ratio;
  final double qtyBtc;
  final double notionalUsd;

  const ScaledOrder({
    required this.ratio,
    required this.qtyBtc,
    required this.notionalUsd,
  });

  @override
  int get hashCode => ratio.hashCode ^ qtyBtc.hashCode ^ notionalUsd.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScaledOrder &&
          runtimeType == other.runtimeType &&
          ratio == other.ratio &&
          qtyBtc == other.qtyBtc &&
          notionalUsd == other.notionalUsd;
}
