// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

enum TelegramActionStatus { pending, simulated, submitted, failed, rejected }

class TelegramClientRequest {
  final int apiId;
  final String apiHash;
  final String phone;
  final PlatformInt64 channelId;
  final String sessionPath;
  final String statePath;

  const TelegramClientRequest({
    required this.apiId,
    required this.apiHash,
    required this.phone,
    required this.channelId,
    required this.sessionPath,
    required this.statePath,
  });

  @override
  int get hashCode =>
      apiId.hashCode ^
      apiHash.hashCode ^
      phone.hashCode ^
      channelId.hashCode ^
      sessionPath.hashCode ^
      statePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TelegramClientRequest &&
          runtimeType == other.runtimeType &&
          apiId == other.apiId &&
          apiHash == other.apiHash &&
          phone == other.phone &&
          channelId == other.channelId &&
          sessionPath == other.sessionPath &&
          statePath == other.statePath;
}

class TelegramLoginStatus {
  final bool ok;
  final bool authorized;
  final bool needsCode;
  final bool needsPassword;
  final String message;

  const TelegramLoginStatus({
    required this.ok,
    required this.authorized,
    required this.needsCode,
    required this.needsPassword,
    required this.message,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      authorized.hashCode ^
      needsCode.hashCode ^
      needsPassword.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TelegramLoginStatus &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          authorized == other.authorized &&
          needsCode == other.needsCode &&
          needsPassword == other.needsPassword &&
          message == other.message;
}

class TelegramMessageEvent {
  final bool ok;
  final PlatformInt64 channelId;
  final String channelTitle;
  final int messageId;
  final List<String> dedupKeys;
  final String text;
  final PlatformInt64 receivedAtMs;
  final String? error;

  const TelegramMessageEvent({
    required this.ok,
    required this.channelId,
    required this.channelTitle,
    required this.messageId,
    required this.dedupKeys,
    required this.text,
    required this.receivedAtMs,
    this.error,
  });

  @override
  int get hashCode =>
      ok.hashCode ^
      channelId.hashCode ^
      channelTitle.hashCode ^
      messageId.hashCode ^
      dedupKeys.hashCode ^
      text.hashCode ^
      receivedAtMs.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TelegramMessageEvent &&
          runtimeType == other.runtimeType &&
          ok == other.ok &&
          channelId == other.channelId &&
          channelTitle == other.channelTitle &&
          messageId == other.messageId &&
          dedupKeys == other.dedupKeys &&
          text == other.text &&
          receivedAtMs == other.receivedAtMs &&
          error == other.error;
}
