// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class PriceTick {
  final String symbol;
  final double? price;
  final double? bid;
  final double? ask;
  final String source;
  final PlatformInt64? eventTimeMs;
  final PlatformInt64 receivedAtMs;
  final bool ok;
  final String? error;

  const PriceTick({
    required this.symbol,
    this.price,
    this.bid,
    this.ask,
    required this.source,
    this.eventTimeMs,
    required this.receivedAtMs,
    required this.ok,
    this.error,
  });

  @override
  int get hashCode =>
      symbol.hashCode ^
      price.hashCode ^
      bid.hashCode ^
      ask.hashCode ^
      source.hashCode ^
      eventTimeMs.hashCode ^
      receivedAtMs.hashCode ^
      ok.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PriceTick &&
          runtimeType == other.runtimeType &&
          symbol == other.symbol &&
          price == other.price &&
          bid == other.bid &&
          ask == other.ask &&
          source == other.source &&
          eventTimeMs == other.eventTimeMs &&
          receivedAtMs == other.receivedAtMs &&
          ok == other.ok &&
          error == other.error;
}

class WeexAccountBalance {
  final String asset;
  final double walletBalance;
  final double availableBalance;
  final double unrealizedPnl;
  final double equity;
  final double usedMargin;

  const WeexAccountBalance({
    required this.asset,
    required this.walletBalance,
    required this.availableBalance,
    required this.unrealizedPnl,
    required this.equity,
    required this.usedMargin,
  });

  @override
  int get hashCode =>
      asset.hashCode ^
      walletBalance.hashCode ^
      availableBalance.hashCode ^
      unrealizedPnl.hashCode ^
      equity.hashCode ^
      usedMargin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WeexAccountBalance &&
          runtimeType == other.runtimeType &&
          asset == other.asset &&
          walletBalance == other.walletBalance &&
          availableBalance == other.availableBalance &&
          unrealizedPnl == other.unrealizedPnl &&
          equity == other.equity &&
          usedMargin == other.usedMargin;
}

class WeexAccountReconciliation {
  final WeexAccountBalance balance;
  final WeexPositionSnapshot position;
  final List<WeexExecutionSnapshot> recentExecutions;
  final PlatformInt64 timestampMs;

  const WeexAccountReconciliation({
    required this.balance,
    required this.position,
    required this.recentExecutions,
    required this.timestampMs,
  });

  @override
  int get hashCode =>
      balance.hashCode ^ position.hashCode ^ recentExecutions.hashCode ^ timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WeexAccountReconciliation &&
          runtimeType == other.runtimeType &&
          balance == other.balance &&
          position == other.position &&
          recentExecutions == other.recentExecutions &&
          timestampMs == other.timestampMs;
}

class WeexAccountRequest {
  final String apiKey;
  final String apiSecret;
  final String passphrase;
  final String symbol;
  final String baseUrl;
  final PlatformInt64 recentLookbackMs;

  const WeexAccountRequest({
    required this.apiKey,
    required this.apiSecret,
    required this.passphrase,
    required this.symbol,
    required this.baseUrl,
    required this.recentLookbackMs,
  });

  @override
  int get hashCode =>
      apiKey.hashCode ^
      apiSecret.hashCode ^
      passphrase.hashCode ^
      symbol.hashCode ^
      baseUrl.hashCode ^
      recentLookbackMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WeexAccountRequest &&
          runtimeType == other.runtimeType &&
          apiKey == other.apiKey &&
          apiSecret == other.apiSecret &&
          passphrase == other.passphrase &&
          symbol == other.symbol &&
          baseUrl == other.baseUrl &&
          recentLookbackMs == other.recentLookbackMs;
}

class WeexAlgoOrderRequest {
  final String apiKey;
  final String apiSecret;
  final String passphrase;
  final String symbol;
  final String baseUrl;
  final String side;
  final double qty;
  final double triggerPrice;
  final double limitPrice;
  final String orderType;
  final String clientAlgoId;
  final double qtyStep;
  final double priceStep;

  const WeexAlgoOrderRequest({
    required this.apiKey,
    required this.apiSecret,
    required this.passphrase,
    required this.symbol,
    required this.baseUrl,
    required this.side,
    required this.qty,
    required this.triggerPrice,
    required this.limitPrice,
    required this.orderType,
    required this.clientAlgoId,
    required this.qtyStep,
    required this.priceStep,
  });

  @override
  int get hashCode =>
      apiKey.hashCode ^
      apiSecret.hashCode ^
      passphrase.hashCode ^
      symbol.hashCode ^
      baseUrl.hashCode ^
      side.hashCode ^
      qty.hashCode ^
      triggerPrice.hashCode ^
      limitPrice.hashCode ^
      orderType.hashCode ^
      clientAlgoId.hashCode ^
      qtyStep.hashCode ^
      priceStep.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WeexAlgoOrderRequest &&
          runtimeType == other.runtimeType &&
          apiKey == other.apiKey &&
          apiSecret == other.apiSecret &&
          passphrase == other.passphrase &&
          symbol == other.symbol &&
          baseUrl == other.baseUrl &&
          side == other.side &&
          qty == other.qty &&
          triggerPrice == other.triggerPrice &&
          limitPrice == other.limitPrice &&
          orderType == other.orderType &&
          clientAlgoId == other.clientAlgoId &&
          qtyStep == other.qtyStep &&
          priceStep == other.priceStep;
}

class WeexCancelAlgoRequest {
  final String apiKey;
  final String apiSecret;
  final String passphrase;
  final String symbol;
  final String baseUrl;
  final String orderId;

  const WeexCancelAlgoRequest({
    required this.apiKey,
    required this.apiSecret,
    required this.passphrase,
    required this.symbol,
    required this.baseUrl,
    required this.orderId,
  });

  @override
  int get hashCode =>
      apiKey.hashCode ^
      apiSecret.hashCode ^
      passphrase.hashCode ^
      symbol.hashCode ^
      baseUrl.hashCode ^
      orderId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WeexCancelAlgoRequest &&
          runtimeType == other.runtimeType &&
          apiKey == other.apiKey &&
          apiSecret == other.apiSecret &&
          passphrase == other.passphrase &&
          symbol == other.symbol &&
          baseUrl == other.baseUrl &&
          orderId == other.orderId;
}

class WeexExecutionSnapshot {
  final String execId;
  final String orderId;
  final String side;
  final String positionSide;
  final String kind;
  final String direction;
  final double price;
  final double qty;
  final double notionalUsdt;
  final double realizedPnlUsdt;
  final double feeUsdt;
  final PlatformInt64 timestampMs;

  const WeexExecutionSnapshot({
    required this.execId,
    required this.orderId,
    required this.side,
    required this.positionSide,
    required this.kind,
    required this.direction,
    required this.price,
    required this.qty,
    required this.notionalUsdt,
    required this.realizedPnlUsdt,
    required this.feeUsdt,
    required this.timestampMs,
  });

  @override
  int get hashCode =>
      execId.hashCode ^
      orderId.hashCode ^
      side.hashCode ^
      positionSide.hashCode ^
      kind.hashCode ^
      direction.hashCode ^
      price.hashCode ^
      qty.hashCode ^
      notionalUsdt.hashCode ^
      realizedPnlUsdt.hashCode ^
      feeUsdt.hashCode ^
      timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WeexExecutionSnapshot &&
          runtimeType == other.runtimeType &&
          execId == other.execId &&
          orderId == other.orderId &&
          side == other.side &&
          positionSide == other.positionSide &&
          kind == other.kind &&
          direction == other.direction &&
          price == other.price &&
          qty == other.qty &&
          notionalUsdt == other.notionalUsdt &&
          realizedPnlUsdt == other.realizedPnlUsdt &&
          feeUsdt == other.feeUsdt &&
          timestampMs == other.timestampMs;
}

class WeexMarketOrderAck {
  final String orderId;
  final String? clientOrderId;
  final bool success;
  final String errorCode;
  final String errorMessage;

  const WeexMarketOrderAck({
    required this.orderId,
    this.clientOrderId,
    required this.success,
    required this.errorCode,
    required this.errorMessage,
  });

  @override
  int get hashCode =>
      orderId.hashCode ^
      clientOrderId.hashCode ^
      success.hashCode ^
      errorCode.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WeexMarketOrderAck &&
          runtimeType == other.runtimeType &&
          orderId == other.orderId &&
          clientOrderId == other.clientOrderId &&
          success == other.success &&
          errorCode == other.errorCode &&
          errorMessage == other.errorMessage;
}

class WeexMarketOrderRequest {
  final String apiKey;
  final String apiSecret;
  final String passphrase;
  final String symbol;
  final String baseUrl;
  final String side;
  final double qty;
  final bool reduceOnly;
  final String clientOrderId;
  final double qtyStep;

  const WeexMarketOrderRequest({
    required this.apiKey,
    required this.apiSecret,
    required this.passphrase,
    required this.symbol,
    required this.baseUrl,
    required this.side,
    required this.qty,
    required this.reduceOnly,
    required this.clientOrderId,
    required this.qtyStep,
  });

  @override
  int get hashCode =>
      apiKey.hashCode ^
      apiSecret.hashCode ^
      passphrase.hashCode ^
      symbol.hashCode ^
      baseUrl.hashCode ^
      side.hashCode ^
      qty.hashCode ^
      reduceOnly.hashCode ^
      clientOrderId.hashCode ^
      qtyStep.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WeexMarketOrderRequest &&
          runtimeType == other.runtimeType &&
          apiKey == other.apiKey &&
          apiSecret == other.apiSecret &&
          passphrase == other.passphrase &&
          symbol == other.symbol &&
          baseUrl == other.baseUrl &&
          side == other.side &&
          qty == other.qty &&
          reduceOnly == other.reduceOnly &&
          clientOrderId == other.clientOrderId &&
          qtyStep == other.qtyStep;
}

/// What the exchange knows about one `client_order_id`.
///
/// `found: false` is a positive statement — the exchange answered and has no
/// such order, so it never landed. An `Err` from [`lookup_order_by_client_id`]
/// means the opposite: we could not find out, and nothing should be retried on
/// the strength of it.
class WeexOrderStatus {
  final bool found;
  final String orderId;
  final String? clientOrderId;

  /// Exchange status verbatim (NEW, PARTIALLY_FILLED, FILLED, CANCELED,
  /// REJECTED), uppercased. Empty when the order is absent.
  final String status;
  final double filledQty;
  final double avgPrice;

  const WeexOrderStatus({
    required this.found,
    required this.orderId,
    this.clientOrderId,
    required this.status,
    required this.filledQty,
    required this.avgPrice,
  });

  @override
  int get hashCode =>
      found.hashCode ^
      orderId.hashCode ^
      clientOrderId.hashCode ^
      status.hashCode ^
      filledQty.hashCode ^
      avgPrice.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WeexOrderStatus &&
          runtimeType == other.runtimeType &&
          found == other.found &&
          orderId == other.orderId &&
          clientOrderId == other.clientOrderId &&
          status == other.status &&
          filledQty == other.filledQty &&
          avgPrice == other.avgPrice;
}

class WeexPositionSnapshot {
  final String symbol;
  final String direction;
  final double qty;
  final double entryPrice;
  final double markPrice;
  final double notionalUsdt;
  final double unrealizedPnlUsdt;
  final double leverage;
  final double? liquidationPrice;
  final PlatformInt64 updatedAtMs;

  const WeexPositionSnapshot({
    required this.symbol,
    required this.direction,
    required this.qty,
    required this.entryPrice,
    required this.markPrice,
    required this.notionalUsdt,
    required this.unrealizedPnlUsdt,
    required this.leverage,
    this.liquidationPrice,
    required this.updatedAtMs,
  });

  @override
  int get hashCode =>
      symbol.hashCode ^
      direction.hashCode ^
      qty.hashCode ^
      entryPrice.hashCode ^
      markPrice.hashCode ^
      notionalUsdt.hashCode ^
      unrealizedPnlUsdt.hashCode ^
      leverage.hashCode ^
      liquidationPrice.hashCode ^
      updatedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WeexPositionSnapshot &&
          runtimeType == other.runtimeType &&
          symbol == other.symbol &&
          direction == other.direction &&
          qty == other.qty &&
          entryPrice == other.entryPrice &&
          markPrice == other.markPrice &&
          notionalUsdt == other.notionalUsdt &&
          unrealizedPnlUsdt == other.unrealizedPnlUsdt &&
          leverage == other.leverage &&
          liquidationPrice == other.liquidationPrice &&
          updatedAtMs == other.updatedAtMs;
}

/// A take-profit (or stop-loss) attached to an open position. Unlike an algo
/// order it carries no side of its own: the exchange closes whatever is open on
/// `position_side` when `trigger_price` is reached, so it stays correct as the
/// position is added to or partially reduced.
class WeexTpSlOrderRequest {
  final String apiKey;
  final String apiSecret;
  final String passphrase;
  final String symbol;
  final String baseUrl;

  /// LONG or SHORT: the position this plan protects.
  final String positionSide;

  /// TAKE_PROFIT or STOP_LOSS.
  final String planType;
  final double triggerPrice;

  /// 0 closes the entire position — the scalping default.
  final double qty;
  final String clientAlgoId;
  final double qtyStep;
  final double priceStep;

  const WeexTpSlOrderRequest({
    required this.apiKey,
    required this.apiSecret,
    required this.passphrase,
    required this.symbol,
    required this.baseUrl,
    required this.positionSide,
    required this.planType,
    required this.triggerPrice,
    required this.qty,
    required this.clientAlgoId,
    required this.qtyStep,
    required this.priceStep,
  });

  @override
  int get hashCode =>
      apiKey.hashCode ^
      apiSecret.hashCode ^
      passphrase.hashCode ^
      symbol.hashCode ^
      baseUrl.hashCode ^
      positionSide.hashCode ^
      planType.hashCode ^
      triggerPrice.hashCode ^
      qty.hashCode ^
      clientAlgoId.hashCode ^
      qtyStep.hashCode ^
      priceStep.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WeexTpSlOrderRequest &&
          runtimeType == other.runtimeType &&
          apiKey == other.apiKey &&
          apiSecret == other.apiSecret &&
          passphrase == other.passphrase &&
          symbol == other.symbol &&
          baseUrl == other.baseUrl &&
          positionSide == other.positionSide &&
          planType == other.planType &&
          triggerPrice == other.triggerPrice &&
          qty == other.qty &&
          clientAlgoId == other.clientAlgoId &&
          qtyStep == other.qtyStep &&
          priceStep == other.priceStep;
}
