// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1239971917;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__chart_data_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "chart_data_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::ChartData::default())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__classify_message_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "classify_message",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_text = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::classify_message(api_text))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__get_balance_history_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_balance_history",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::get_balance_history())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__get_chart_data_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_chart_data",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::get_chart_data())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__get_equity_history_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_equity_history",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::get_equity_history())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__get_pnl_history_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_pnl_history",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::get_pnl_history())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__hello_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "hello",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::hello())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__record_chart_snapshot_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "record_chart_snapshot",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_timestamp_ms = <i64>::sse_decode(&mut deserializer);
            let api_balance = <f64>::sse_decode(&mut deserializer);
            let api_equity = <f64>::sse_decode(&mut deserializer);
            let api_cumulative_pnl = <f64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::record_chart_snapshot(
                            api_timestamp_ms,
                            api_balance,
                            api_equity,
                            api_cumulative_pnl,
                        );
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__scale_manual_order_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "scale_manual_order",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request = <crate::api::ManualScaleRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::scale_manual_order(api_request))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__weex_public_price_stream_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "weex_public_price_stream",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink = <StreamSink<
                crate::weex::PriceTick,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok({
                            crate::api::weex_public_price_stream(api_sink).await;
                        })?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__weex_reconcile_account_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "weex_reconcile_account",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request = <crate::weex::WeexAccountRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok(
                            crate::api::weex_reconcile_account(api_request).await,
                        )?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__weex_sign_preview_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "weex_sign_preview",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_secret = <String>::sse_decode(&mut deserializer);
            let api_timestamp = <i64>::sse_decode(&mut deserializer);
            let api_method = <String>::sse_decode(&mut deserializer);
            let api_path = <String>::sse_decode(&mut deserializer);
            let api_query = <String>::sse_decode(&mut deserializer);
            let api_body = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::weex_sign_preview(
                        api_secret,
                        api_timestamp,
                        api_method,
                        api_path,
                        api_query,
                        api_body,
                    ))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__weex_submit_market_order_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "weex_submit_market_order",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request = <crate::weex::WeexMarketOrderRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok(
                            crate::api::weex_submit_market_order(api_request).await,
                        )?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<crate::weex::PriceTick, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::interpreter::Action {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <crate::interpreter::ActionKind>::sse_decode(deserializer);
        let mut var_direction = <Option<crate::interpreter::Direction>>::sse_decode(deserializer);
        let mut var_size = <Option<crate::interpreter::Size>>::sse_decode(deserializer);
        let mut var_confidenceHigh = <bool>::sse_decode(deserializer);
        let mut var_needsApproval = <bool>::sse_decode(deserializer);
        let mut var_rawText = <String>::sse_decode(deserializer);
        return crate::interpreter::Action {
            kind: var_kind,
            direction: var_direction,
            size: var_size,
            confidence_high: var_confidenceHigh,
            needs_approval: var_needsApproval,
            raw_text: var_rawText,
        };
    }
}

impl SseDecode for crate::interpreter::ActionKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::interpreter::ActionKind::Enter,
            1 => crate::interpreter::ActionKind::Add,
            2 => crate::interpreter::ActionKind::Reduce,
            3 => crate::interpreter::ActionKind::Close,
            4 => crate::interpreter::ActionKind::Ignore,
            _ => unreachable!("Invalid variant for ActionKind: {}", inner),
        };
    }
}

impl SseDecode for crate::api::ApiResultAction {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_ok = <bool>::sse_decode(deserializer);
        let mut var_value = <Option<crate::interpreter::Action>>::sse_decode(deserializer);
        let mut var_error = <Option<String>>::sse_decode(deserializer);
        return crate::api::ApiResultAction {
            ok: var_ok,
            value: var_value,
            error: var_error,
        };
    }
}

impl SseDecode for crate::api::ApiResultScaledOrder {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_ok = <bool>::sse_decode(deserializer);
        let mut var_value = <Option<crate::scaling::ScaledOrder>>::sse_decode(deserializer);
        let mut var_error = <Option<String>>::sse_decode(deserializer);
        return crate::api::ApiResultScaledOrder {
            ok: var_ok,
            value: var_value,
            error: var_error,
        };
    }
}

impl SseDecode for crate::api::ApiResultString {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_ok = <bool>::sse_decode(deserializer);
        let mut var_value = <Option<String>>::sse_decode(deserializer);
        let mut var_error = <Option<String>>::sse_decode(deserializer);
        return crate::api::ApiResultString {
            ok: var_ok,
            value: var_value,
            error: var_error,
        };
    }
}

impl SseDecode for crate::api::ApiResultWeexAccountReconciliation {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_ok = <bool>::sse_decode(deserializer);
        let mut var_value =
            <Option<crate::weex::WeexAccountReconciliation>>::sse_decode(deserializer);
        let mut var_error = <Option<String>>::sse_decode(deserializer);
        return crate::api::ApiResultWeexAccountReconciliation {
            ok: var_ok,
            value: var_value,
            error: var_error,
        };
    }
}

impl SseDecode for crate::api::ApiResultWeexMarketOrderAck {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_ok = <bool>::sse_decode(deserializer);
        let mut var_value = <Option<crate::weex::WeexMarketOrderAck>>::sse_decode(deserializer);
        let mut var_error = <Option<String>>::sse_decode(deserializer);
        return crate::api::ApiResultWeexMarketOrderAck {
            ok: var_ok,
            value: var_value,
            error: var_error,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::ChartData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_balance = <Vec<crate::api::SeriesPoint>>::sse_decode(deserializer);
        let mut var_equity = <Vec<crate::api::SeriesPoint>>::sse_decode(deserializer);
        let mut var_pnl = <Vec<crate::api::SeriesPoint>>::sse_decode(deserializer);
        return crate::api::ChartData {
            balance: var_balance,
            equity: var_equity,
            pnl: var_pnl,
        };
    }
}

impl SseDecode for crate::interpreter::Direction {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::interpreter::Direction::Long,
            1 => crate::interpreter::Direction::Short,
            _ => unreachable!("Invalid variant for Direction: {}", inner),
        };
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::SeriesPoint> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::SeriesPoint>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::weex::WeexExecutionSnapshot> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::weex::WeexExecutionSnapshot>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::ManualScaleRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_amount = <f64>::sse_decode(deserializer);
        let mut var_unit = <crate::api::ManualSizeUnit>::sse_decode(deserializer);
        let mut var_masterBalanceUsd = <f64>::sse_decode(deserializer);
        let mut var_myBalanceUsd = <f64>::sse_decode(deserializer);
        let mut var_markPrice = <f64>::sse_decode(deserializer);
        let mut var_qtyStep = <f64>::sse_decode(deserializer);
        return crate::api::ManualScaleRequest {
            amount: var_amount,
            unit: var_unit,
            master_balance_usd: var_masterBalanceUsd,
            my_balance_usd: var_myBalanceUsd,
            mark_price: var_markPrice,
            qty_step: var_qtyStep,
        };
    }
}

impl SseDecode for crate::api::ManualSizeUnit {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::ManualSizeUnit::Btc,
            1 => crate::api::ManualSizeUnit::Usdt,
            _ => unreachable!("Invalid variant for ManualSizeUnit: {}", inner),
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::interpreter::Action> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::interpreter::Action>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::interpreter::Direction> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::interpreter::Direction>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<f64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<i64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::scaling::ScaledOrder> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::scaling::ScaledOrder>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::interpreter::Size> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::interpreter::Size>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::weex::WeexAccountReconciliation> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::weex::WeexAccountReconciliation>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::weex::WeexMarketOrderAck> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::weex::WeexMarketOrderAck>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::weex::PriceTick {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_symbol = <String>::sse_decode(deserializer);
        let mut var_price = <Option<f64>>::sse_decode(deserializer);
        let mut var_bid = <Option<f64>>::sse_decode(deserializer);
        let mut var_ask = <Option<f64>>::sse_decode(deserializer);
        let mut var_source = <String>::sse_decode(deserializer);
        let mut var_eventTimeMs = <Option<i64>>::sse_decode(deserializer);
        let mut var_receivedAtMs = <i64>::sse_decode(deserializer);
        let mut var_ok = <bool>::sse_decode(deserializer);
        let mut var_error = <Option<String>>::sse_decode(deserializer);
        return crate::weex::PriceTick {
            symbol: var_symbol,
            price: var_price,
            bid: var_bid,
            ask: var_ask,
            source: var_source,
            event_time_ms: var_eventTimeMs,
            received_at_ms: var_receivedAtMs,
            ok: var_ok,
            error: var_error,
        };
    }
}

impl SseDecode for crate::scaling::ScaledOrder {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_ratio = <f64>::sse_decode(deserializer);
        let mut var_qtyBtc = <f64>::sse_decode(deserializer);
        let mut var_notionalUsd = <f64>::sse_decode(deserializer);
        return crate::scaling::ScaledOrder {
            ratio: var_ratio,
            qty_btc: var_qtyBtc,
            notional_usd: var_notionalUsd,
        };
    }
}

impl SseDecode for crate::api::SeriesPoint {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_timestampMs = <i64>::sse_decode(deserializer);
        let mut var_value = <f64>::sse_decode(deserializer);
        return crate::api::SeriesPoint {
            timestamp_ms: var_timestampMs,
            value: var_value,
        };
    }
}

impl SseDecode for crate::interpreter::Size {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_field0 = <f64>::sse_decode(deserializer);
                return crate::interpreter::Size::Usd(var_field0);
            }
            1 => {
                let mut var_field0 = <f64>::sse_decode(deserializer);
                return crate::interpreter::Size::Btc(var_field0);
            }
            2 => {
                let mut var_field0 = <f64>::sse_decode(deserializer);
                return crate::interpreter::Size::Pct(var_field0);
            }
            3 => {
                return crate::interpreter::Size::FullClose;
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::weex::WeexAccountBalance {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_asset = <String>::sse_decode(deserializer);
        let mut var_walletBalance = <f64>::sse_decode(deserializer);
        let mut var_availableBalance = <f64>::sse_decode(deserializer);
        let mut var_unrealizedPnl = <f64>::sse_decode(deserializer);
        let mut var_equity = <f64>::sse_decode(deserializer);
        let mut var_usedMargin = <f64>::sse_decode(deserializer);
        return crate::weex::WeexAccountBalance {
            asset: var_asset,
            wallet_balance: var_walletBalance,
            available_balance: var_availableBalance,
            unrealized_pnl: var_unrealizedPnl,
            equity: var_equity,
            used_margin: var_usedMargin,
        };
    }
}

impl SseDecode for crate::weex::WeexAccountReconciliation {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_balance = <crate::weex::WeexAccountBalance>::sse_decode(deserializer);
        let mut var_position = <crate::weex::WeexPositionSnapshot>::sse_decode(deserializer);
        let mut var_recentExecutions =
            <Vec<crate::weex::WeexExecutionSnapshot>>::sse_decode(deserializer);
        let mut var_timestampMs = <i64>::sse_decode(deserializer);
        return crate::weex::WeexAccountReconciliation {
            balance: var_balance,
            position: var_position,
            recent_executions: var_recentExecutions,
            timestamp_ms: var_timestampMs,
        };
    }
}

impl SseDecode for crate::weex::WeexAccountRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_apiKey = <String>::sse_decode(deserializer);
        let mut var_apiSecret = <String>::sse_decode(deserializer);
        let mut var_passphrase = <String>::sse_decode(deserializer);
        let mut var_symbol = <String>::sse_decode(deserializer);
        let mut var_baseUrl = <String>::sse_decode(deserializer);
        let mut var_recentLookbackMs = <i64>::sse_decode(deserializer);
        return crate::weex::WeexAccountRequest {
            api_key: var_apiKey,
            api_secret: var_apiSecret,
            passphrase: var_passphrase,
            symbol: var_symbol,
            base_url: var_baseUrl,
            recent_lookback_ms: var_recentLookbackMs,
        };
    }
}

impl SseDecode for crate::weex::WeexExecutionSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_execId = <String>::sse_decode(deserializer);
        let mut var_orderId = <String>::sse_decode(deserializer);
        let mut var_side = <String>::sse_decode(deserializer);
        let mut var_positionSide = <String>::sse_decode(deserializer);
        let mut var_kind = <String>::sse_decode(deserializer);
        let mut var_direction = <String>::sse_decode(deserializer);
        let mut var_price = <f64>::sse_decode(deserializer);
        let mut var_qtyBtc = <f64>::sse_decode(deserializer);
        let mut var_notionalUsdt = <f64>::sse_decode(deserializer);
        let mut var_realizedPnlUsdt = <f64>::sse_decode(deserializer);
        let mut var_feeUsdt = <f64>::sse_decode(deserializer);
        let mut var_timestampMs = <i64>::sse_decode(deserializer);
        return crate::weex::WeexExecutionSnapshot {
            exec_id: var_execId,
            order_id: var_orderId,
            side: var_side,
            position_side: var_positionSide,
            kind: var_kind,
            direction: var_direction,
            price: var_price,
            qty_btc: var_qtyBtc,
            notional_usdt: var_notionalUsdt,
            realized_pnl_usdt: var_realizedPnlUsdt,
            fee_usdt: var_feeUsdt,
            timestamp_ms: var_timestampMs,
        };
    }
}

impl SseDecode for crate::weex::WeexMarketOrderAck {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_orderId = <String>::sse_decode(deserializer);
        let mut var_clientOrderId = <Option<String>>::sse_decode(deserializer);
        let mut var_success = <bool>::sse_decode(deserializer);
        let mut var_errorCode = <String>::sse_decode(deserializer);
        let mut var_errorMessage = <String>::sse_decode(deserializer);
        return crate::weex::WeexMarketOrderAck {
            order_id: var_orderId,
            client_order_id: var_clientOrderId,
            success: var_success,
            error_code: var_errorCode,
            error_message: var_errorMessage,
        };
    }
}

impl SseDecode for crate::weex::WeexMarketOrderRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_apiKey = <String>::sse_decode(deserializer);
        let mut var_apiSecret = <String>::sse_decode(deserializer);
        let mut var_passphrase = <String>::sse_decode(deserializer);
        let mut var_symbol = <String>::sse_decode(deserializer);
        let mut var_baseUrl = <String>::sse_decode(deserializer);
        let mut var_side = <String>::sse_decode(deserializer);
        let mut var_qtyBtc = <f64>::sse_decode(deserializer);
        let mut var_reduceOnly = <bool>::sse_decode(deserializer);
        let mut var_clientOrderId = <String>::sse_decode(deserializer);
        let mut var_qtyStep = <f64>::sse_decode(deserializer);
        return crate::weex::WeexMarketOrderRequest {
            api_key: var_apiKey,
            api_secret: var_apiSecret,
            passphrase: var_passphrase,
            symbol: var_symbol,
            base_url: var_baseUrl,
            side: var_side,
            qty_btc: var_qtyBtc,
            reduce_only: var_reduceOnly,
            client_order_id: var_clientOrderId,
            qty_step: var_qtyStep,
        };
    }
}

impl SseDecode for crate::weex::WeexPositionSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_symbol = <String>::sse_decode(deserializer);
        let mut var_direction = <String>::sse_decode(deserializer);
        let mut var_qtyBtc = <f64>::sse_decode(deserializer);
        let mut var_entryPrice = <f64>::sse_decode(deserializer);
        let mut var_markPrice = <f64>::sse_decode(deserializer);
        let mut var_notionalUsdt = <f64>::sse_decode(deserializer);
        let mut var_unrealizedPnlUsdt = <f64>::sse_decode(deserializer);
        let mut var_leverage = <f64>::sse_decode(deserializer);
        let mut var_liquidationPrice = <Option<f64>>::sse_decode(deserializer);
        let mut var_updatedAtMs = <i64>::sse_decode(deserializer);
        return crate::weex::WeexPositionSnapshot {
            symbol: var_symbol,
            direction: var_direction,
            qty_btc: var_qtyBtc,
            entry_price: var_entryPrice,
            mark_price: var_markPrice,
            notional_usdt: var_notionalUsdt,
            unrealized_pnl_usdt: var_unrealizedPnlUsdt,
            leverage: var_leverage,
            liquidation_price: var_liquidationPrice,
            updated_at_ms: var_updatedAtMs,
        };
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__chart_data_default_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__classify_message_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__get_balance_history_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__get_chart_data_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__api__get_equity_history_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__get_pnl_history_impl(port, ptr, rust_vec_len, data_len),
        7 => wire__crate__api__hello_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__api__record_chart_snapshot_impl(port, ptr, rust_vec_len, data_len),
        9 => wire__crate__api__scale_manual_order_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__api__weex_public_price_stream_impl(port, ptr, rust_vec_len, data_len),
        11 => wire__crate__api__weex_reconcile_account_impl(port, ptr, rust_vec_len, data_len),
        12 => wire__crate__api__weex_sign_preview_impl(port, ptr, rust_vec_len, data_len),
        13 => wire__crate__api__weex_submit_market_order_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::interpreter::Action {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.direction.into_into_dart().into_dart(),
            self.size.into_into_dart().into_dart(),
            self.confidence_high.into_into_dart().into_dart(),
            self.needs_approval.into_into_dart().into_dart(),
            self.raw_text.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::interpreter::Action {}
impl flutter_rust_bridge::IntoIntoDart<crate::interpreter::Action> for crate::interpreter::Action {
    fn into_into_dart(self) -> crate::interpreter::Action {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::interpreter::ActionKind {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Enter => 0.into_dart(),
            Self::Add => 1.into_dart(),
            Self::Reduce => 2.into_dart(),
            Self::Close => 3.into_dart(),
            Self::Ignore => 4.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::interpreter::ActionKind
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::interpreter::ActionKind>
    for crate::interpreter::ActionKind
{
    fn into_into_dart(self) -> crate::interpreter::ActionKind {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::ApiResultAction {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.ok.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
            self.error.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::ApiResultAction {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::ApiResultAction>
    for crate::api::ApiResultAction
{
    fn into_into_dart(self) -> crate::api::ApiResultAction {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::ApiResultScaledOrder {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.ok.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
            self.error.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::ApiResultScaledOrder
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::ApiResultScaledOrder>
    for crate::api::ApiResultScaledOrder
{
    fn into_into_dart(self) -> crate::api::ApiResultScaledOrder {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::ApiResultString {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.ok.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
            self.error.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::ApiResultString {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::ApiResultString>
    for crate::api::ApiResultString
{
    fn into_into_dart(self) -> crate::api::ApiResultString {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::ApiResultWeexAccountReconciliation {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.ok.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
            self.error.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::ApiResultWeexAccountReconciliation
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::ApiResultWeexAccountReconciliation>
    for crate::api::ApiResultWeexAccountReconciliation
{
    fn into_into_dart(self) -> crate::api::ApiResultWeexAccountReconciliation {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::ApiResultWeexMarketOrderAck {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.ok.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
            self.error.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::ApiResultWeexMarketOrderAck
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::ApiResultWeexMarketOrderAck>
    for crate::api::ApiResultWeexMarketOrderAck
{
    fn into_into_dart(self) -> crate::api::ApiResultWeexMarketOrderAck {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::ChartData {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.balance.into_into_dart().into_dart(),
            self.equity.into_into_dart().into_dart(),
            self.pnl.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::ChartData {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::ChartData> for crate::api::ChartData {
    fn into_into_dart(self) -> crate::api::ChartData {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::interpreter::Direction {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Long => 0.into_dart(),
            Self::Short => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::interpreter::Direction {}
impl flutter_rust_bridge::IntoIntoDart<crate::interpreter::Direction>
    for crate::interpreter::Direction
{
    fn into_into_dart(self) -> crate::interpreter::Direction {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::ManualScaleRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.amount.into_into_dart().into_dart(),
            self.unit.into_into_dart().into_dart(),
            self.master_balance_usd.into_into_dart().into_dart(),
            self.my_balance_usd.into_into_dart().into_dart(),
            self.mark_price.into_into_dart().into_dart(),
            self.qty_step.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::ManualScaleRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::ManualScaleRequest>
    for crate::api::ManualScaleRequest
{
    fn into_into_dart(self) -> crate::api::ManualScaleRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::ManualSizeUnit {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Btc => 0.into_dart(),
            Self::Usdt => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::ManualSizeUnit {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::ManualSizeUnit> for crate::api::ManualSizeUnit {
    fn into_into_dart(self) -> crate::api::ManualSizeUnit {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::weex::PriceTick {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.symbol.into_into_dart().into_dart(),
            self.price.into_into_dart().into_dart(),
            self.bid.into_into_dart().into_dart(),
            self.ask.into_into_dart().into_dart(),
            self.source.into_into_dart().into_dart(),
            self.event_time_ms.into_into_dart().into_dart(),
            self.received_at_ms.into_into_dart().into_dart(),
            self.ok.into_into_dart().into_dart(),
            self.error.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::weex::PriceTick {}
impl flutter_rust_bridge::IntoIntoDart<crate::weex::PriceTick> for crate::weex::PriceTick {
    fn into_into_dart(self) -> crate::weex::PriceTick {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::scaling::ScaledOrder {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.ratio.into_into_dart().into_dart(),
            self.qty_btc.into_into_dart().into_dart(),
            self.notional_usd.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::scaling::ScaledOrder {}
impl flutter_rust_bridge::IntoIntoDart<crate::scaling::ScaledOrder>
    for crate::scaling::ScaledOrder
{
    fn into_into_dart(self) -> crate::scaling::ScaledOrder {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::SeriesPoint {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.timestamp_ms.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::SeriesPoint {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::SeriesPoint> for crate::api::SeriesPoint {
    fn into_into_dart(self) -> crate::api::SeriesPoint {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::interpreter::Size {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::interpreter::Size::Usd(field0) => {
                [0.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::interpreter::Size::Btc(field0) => {
                [1.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::interpreter::Size::Pct(field0) => {
                [2.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::interpreter::Size::FullClose => [3.into_dart()].into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::interpreter::Size {}
impl flutter_rust_bridge::IntoIntoDart<crate::interpreter::Size> for crate::interpreter::Size {
    fn into_into_dart(self) -> crate::interpreter::Size {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::weex::WeexAccountBalance {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.asset.into_into_dart().into_dart(),
            self.wallet_balance.into_into_dart().into_dart(),
            self.available_balance.into_into_dart().into_dart(),
            self.unrealized_pnl.into_into_dart().into_dart(),
            self.equity.into_into_dart().into_dart(),
            self.used_margin.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::weex::WeexAccountBalance
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::weex::WeexAccountBalance>
    for crate::weex::WeexAccountBalance
{
    fn into_into_dart(self) -> crate::weex::WeexAccountBalance {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::weex::WeexAccountReconciliation {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.balance.into_into_dart().into_dart(),
            self.position.into_into_dart().into_dart(),
            self.recent_executions.into_into_dart().into_dart(),
            self.timestamp_ms.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::weex::WeexAccountReconciliation
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::weex::WeexAccountReconciliation>
    for crate::weex::WeexAccountReconciliation
{
    fn into_into_dart(self) -> crate::weex::WeexAccountReconciliation {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::weex::WeexAccountRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.api_key.into_into_dart().into_dart(),
            self.api_secret.into_into_dart().into_dart(),
            self.passphrase.into_into_dart().into_dart(),
            self.symbol.into_into_dart().into_dart(),
            self.base_url.into_into_dart().into_dart(),
            self.recent_lookback_ms.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::weex::WeexAccountRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::weex::WeexAccountRequest>
    for crate::weex::WeexAccountRequest
{
    fn into_into_dart(self) -> crate::weex::WeexAccountRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::weex::WeexExecutionSnapshot {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.exec_id.into_into_dart().into_dart(),
            self.order_id.into_into_dart().into_dart(),
            self.side.into_into_dart().into_dart(),
            self.position_side.into_into_dart().into_dart(),
            self.kind.into_into_dart().into_dart(),
            self.direction.into_into_dart().into_dart(),
            self.price.into_into_dart().into_dart(),
            self.qty_btc.into_into_dart().into_dart(),
            self.notional_usdt.into_into_dart().into_dart(),
            self.realized_pnl_usdt.into_into_dart().into_dart(),
            self.fee_usdt.into_into_dart().into_dart(),
            self.timestamp_ms.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::weex::WeexExecutionSnapshot
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::weex::WeexExecutionSnapshot>
    for crate::weex::WeexExecutionSnapshot
{
    fn into_into_dart(self) -> crate::weex::WeexExecutionSnapshot {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::weex::WeexMarketOrderAck {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.order_id.into_into_dart().into_dart(),
            self.client_order_id.into_into_dart().into_dart(),
            self.success.into_into_dart().into_dart(),
            self.error_code.into_into_dart().into_dart(),
            self.error_message.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::weex::WeexMarketOrderAck
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::weex::WeexMarketOrderAck>
    for crate::weex::WeexMarketOrderAck
{
    fn into_into_dart(self) -> crate::weex::WeexMarketOrderAck {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::weex::WeexMarketOrderRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.api_key.into_into_dart().into_dart(),
            self.api_secret.into_into_dart().into_dart(),
            self.passphrase.into_into_dart().into_dart(),
            self.symbol.into_into_dart().into_dart(),
            self.base_url.into_into_dart().into_dart(),
            self.side.into_into_dart().into_dart(),
            self.qty_btc.into_into_dart().into_dart(),
            self.reduce_only.into_into_dart().into_dart(),
            self.client_order_id.into_into_dart().into_dart(),
            self.qty_step.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::weex::WeexMarketOrderRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::weex::WeexMarketOrderRequest>
    for crate::weex::WeexMarketOrderRequest
{
    fn into_into_dart(self) -> crate::weex::WeexMarketOrderRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::weex::WeexPositionSnapshot {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.symbol.into_into_dart().into_dart(),
            self.direction.into_into_dart().into_dart(),
            self.qty_btc.into_into_dart().into_dart(),
            self.entry_price.into_into_dart().into_dart(),
            self.mark_price.into_into_dart().into_dart(),
            self.notional_usdt.into_into_dart().into_dart(),
            self.unrealized_pnl_usdt.into_into_dart().into_dart(),
            self.leverage.into_into_dart().into_dart(),
            self.liquidation_price.into_into_dart().into_dart(),
            self.updated_at_ms.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::weex::WeexPositionSnapshot
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::weex::WeexPositionSnapshot>
    for crate::weex::WeexPositionSnapshot
{
    fn into_into_dart(self) -> crate::weex::WeexPositionSnapshot {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<crate::weex::PriceTick, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::interpreter::Action {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::interpreter::ActionKind>::sse_encode(self.kind, serializer);
        <Option<crate::interpreter::Direction>>::sse_encode(self.direction, serializer);
        <Option<crate::interpreter::Size>>::sse_encode(self.size, serializer);
        <bool>::sse_encode(self.confidence_high, serializer);
        <bool>::sse_encode(self.needs_approval, serializer);
        <String>::sse_encode(self.raw_text, serializer);
    }
}

impl SseEncode for crate::interpreter::ActionKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::interpreter::ActionKind::Enter => 0,
                crate::interpreter::ActionKind::Add => 1,
                crate::interpreter::ActionKind::Reduce => 2,
                crate::interpreter::ActionKind::Close => 3,
                crate::interpreter::ActionKind::Ignore => 4,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::ApiResultAction {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.ok, serializer);
        <Option<crate::interpreter::Action>>::sse_encode(self.value, serializer);
        <Option<String>>::sse_encode(self.error, serializer);
    }
}

impl SseEncode for crate::api::ApiResultScaledOrder {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.ok, serializer);
        <Option<crate::scaling::ScaledOrder>>::sse_encode(self.value, serializer);
        <Option<String>>::sse_encode(self.error, serializer);
    }
}

impl SseEncode for crate::api::ApiResultString {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.ok, serializer);
        <Option<String>>::sse_encode(self.value, serializer);
        <Option<String>>::sse_encode(self.error, serializer);
    }
}

impl SseEncode for crate::api::ApiResultWeexAccountReconciliation {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.ok, serializer);
        <Option<crate::weex::WeexAccountReconciliation>>::sse_encode(self.value, serializer);
        <Option<String>>::sse_encode(self.error, serializer);
    }
}

impl SseEncode for crate::api::ApiResultWeexMarketOrderAck {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.ok, serializer);
        <Option<crate::weex::WeexMarketOrderAck>>::sse_encode(self.value, serializer);
        <Option<String>>::sse_encode(self.error, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::ChartData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::api::SeriesPoint>>::sse_encode(self.balance, serializer);
        <Vec<crate::api::SeriesPoint>>::sse_encode(self.equity, serializer);
        <Vec<crate::api::SeriesPoint>>::sse_encode(self.pnl, serializer);
    }
}

impl SseEncode for crate::interpreter::Direction {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::interpreter::Direction::Long => 0,
                crate::interpreter::Direction::Short => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::SeriesPoint> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::SeriesPoint>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::weex::WeexExecutionSnapshot> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::weex::WeexExecutionSnapshot>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::ManualScaleRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f64>::sse_encode(self.amount, serializer);
        <crate::api::ManualSizeUnit>::sse_encode(self.unit, serializer);
        <f64>::sse_encode(self.master_balance_usd, serializer);
        <f64>::sse_encode(self.my_balance_usd, serializer);
        <f64>::sse_encode(self.mark_price, serializer);
        <f64>::sse_encode(self.qty_step, serializer);
    }
}

impl SseEncode for crate::api::ManualSizeUnit {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::ManualSizeUnit::Btc => 0,
                crate::api::ManualSizeUnit::Usdt => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::interpreter::Action> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::interpreter::Action>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::interpreter::Direction> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::interpreter::Direction>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <f64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <i64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::scaling::ScaledOrder> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::scaling::ScaledOrder>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::interpreter::Size> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::interpreter::Size>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::weex::WeexAccountReconciliation> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::weex::WeexAccountReconciliation>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::weex::WeexMarketOrderAck> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::weex::WeexMarketOrderAck>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::weex::PriceTick {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.symbol, serializer);
        <Option<f64>>::sse_encode(self.price, serializer);
        <Option<f64>>::sse_encode(self.bid, serializer);
        <Option<f64>>::sse_encode(self.ask, serializer);
        <String>::sse_encode(self.source, serializer);
        <Option<i64>>::sse_encode(self.event_time_ms, serializer);
        <i64>::sse_encode(self.received_at_ms, serializer);
        <bool>::sse_encode(self.ok, serializer);
        <Option<String>>::sse_encode(self.error, serializer);
    }
}

impl SseEncode for crate::scaling::ScaledOrder {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f64>::sse_encode(self.ratio, serializer);
        <f64>::sse_encode(self.qty_btc, serializer);
        <f64>::sse_encode(self.notional_usd, serializer);
    }
}

impl SseEncode for crate::api::SeriesPoint {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.timestamp_ms, serializer);
        <f64>::sse_encode(self.value, serializer);
    }
}

impl SseEncode for crate::interpreter::Size {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::interpreter::Size::Usd(field0) => {
                <i32>::sse_encode(0, serializer);
                <f64>::sse_encode(field0, serializer);
            }
            crate::interpreter::Size::Btc(field0) => {
                <i32>::sse_encode(1, serializer);
                <f64>::sse_encode(field0, serializer);
            }
            crate::interpreter::Size::Pct(field0) => {
                <i32>::sse_encode(2, serializer);
                <f64>::sse_encode(field0, serializer);
            }
            crate::interpreter::Size::FullClose => {
                <i32>::sse_encode(3, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::weex::WeexAccountBalance {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.asset, serializer);
        <f64>::sse_encode(self.wallet_balance, serializer);
        <f64>::sse_encode(self.available_balance, serializer);
        <f64>::sse_encode(self.unrealized_pnl, serializer);
        <f64>::sse_encode(self.equity, serializer);
        <f64>::sse_encode(self.used_margin, serializer);
    }
}

impl SseEncode for crate::weex::WeexAccountReconciliation {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::weex::WeexAccountBalance>::sse_encode(self.balance, serializer);
        <crate::weex::WeexPositionSnapshot>::sse_encode(self.position, serializer);
        <Vec<crate::weex::WeexExecutionSnapshot>>::sse_encode(self.recent_executions, serializer);
        <i64>::sse_encode(self.timestamp_ms, serializer);
    }
}

impl SseEncode for crate::weex::WeexAccountRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.api_key, serializer);
        <String>::sse_encode(self.api_secret, serializer);
        <String>::sse_encode(self.passphrase, serializer);
        <String>::sse_encode(self.symbol, serializer);
        <String>::sse_encode(self.base_url, serializer);
        <i64>::sse_encode(self.recent_lookback_ms, serializer);
    }
}

impl SseEncode for crate::weex::WeexExecutionSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.exec_id, serializer);
        <String>::sse_encode(self.order_id, serializer);
        <String>::sse_encode(self.side, serializer);
        <String>::sse_encode(self.position_side, serializer);
        <String>::sse_encode(self.kind, serializer);
        <String>::sse_encode(self.direction, serializer);
        <f64>::sse_encode(self.price, serializer);
        <f64>::sse_encode(self.qty_btc, serializer);
        <f64>::sse_encode(self.notional_usdt, serializer);
        <f64>::sse_encode(self.realized_pnl_usdt, serializer);
        <f64>::sse_encode(self.fee_usdt, serializer);
        <i64>::sse_encode(self.timestamp_ms, serializer);
    }
}

impl SseEncode for crate::weex::WeexMarketOrderAck {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.order_id, serializer);
        <Option<String>>::sse_encode(self.client_order_id, serializer);
        <bool>::sse_encode(self.success, serializer);
        <String>::sse_encode(self.error_code, serializer);
        <String>::sse_encode(self.error_message, serializer);
    }
}

impl SseEncode for crate::weex::WeexMarketOrderRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.api_key, serializer);
        <String>::sse_encode(self.api_secret, serializer);
        <String>::sse_encode(self.passphrase, serializer);
        <String>::sse_encode(self.symbol, serializer);
        <String>::sse_encode(self.base_url, serializer);
        <String>::sse_encode(self.side, serializer);
        <f64>::sse_encode(self.qty_btc, serializer);
        <bool>::sse_encode(self.reduce_only, serializer);
        <String>::sse_encode(self.client_order_id, serializer);
        <f64>::sse_encode(self.qty_step, serializer);
    }
}

impl SseEncode for crate::weex::WeexPositionSnapshot {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.symbol, serializer);
        <String>::sse_encode(self.direction, serializer);
        <f64>::sse_encode(self.qty_btc, serializer);
        <f64>::sse_encode(self.entry_price, serializer);
        <f64>::sse_encode(self.mark_price, serializer);
        <f64>::sse_encode(self.notional_usdt, serializer);
        <f64>::sse_encode(self.unrealized_pnl_usdt, serializer);
        <f64>::sse_encode(self.leverage, serializer);
        <Option<f64>>::sse_encode(self.liquidation_price, serializer);
        <i64>::sse_encode(self.updated_at_ms, serializer);
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
